"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { ensureGuestAccount } from "@/lib/auth/store";

export type Language = "ko" | "en" | "ru" | "zh" | "ja" | "zh-TW" | "th";

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ko: {
    // Navigation
    home: "홈",
    map: "여행",
    learn: "학습",
    chat: "대화",
    vocab: "단어장",
    me: "나",
    myPage: "마이페이지",
    mateRouteTitle: "{name} 기장과의 노선",
    changeMate: "변경 ›",
    selectMateTitle: "메이트 선택",
    selectMateSub: "함께 학습할 기장을 선택해 주세요.",
    mateTagline_kyuhyun: "서울·경기 노선을 담당하는 능글맞고 다정한 베테랑 기장",
    mateTagline_haneul: "전주·전라 노선을 담당하는 무뚝뚝하지만 다정한 연하 기장",
    mateTagline_sunwoo: "부산·경남 노선을 담당하는 장난기 많은 소꿉친구 기장",
    mateTagline_sangwoo: "충청·공주 노선을 담당하는 FM 성격의 관제 기장",
    mateTagline_yongwoo: "제주 노선을 담당하는 친형제 같은 츤데레 기장",
    loadingTakeoff: "떠날 준비를 하고 있어요...",
    galleryTitle: "사진첩",
    galleryEmptyMsg: "아직 준비된 사진이 없어요.",
    gallerySoftLockNotice: "코인으로 해금한 사진은 계정에 저장돼요.",

    settingsAccount: "설정 · 계정",
    settingsGeneral: "설정 · 일반",
    settingsLegal: "설정 · 법률 & 지원",
    settingsOther: "기타",
    editProfile: "개인정보 변경",
    paymentMethods: "결제 수단 관리",
    securitySettings: "보안 설정",
    notificationSettings: "알림 설정",
    themeSettings: "테마 설정",
    themeSettingsSub: "화면 테마를 선택해 주세요.",
    themeLight: "라이트 모드",
    themeLightSub: "밝고 깔끔한 화면",
    themeDark: "다크 모드",
    themeDarkSub: "야간에 눈이 편안한 화면",
    termsOfService: "이용약관",
    privacyPolicy: "개인정보처리방침",
    customerSupport: "고객 지원",
    appVersion: "앱 버전",
    backToMyPage: "‹ 마이페이지로 돌아가기",
    savingBtn: "저장 중...",

    nameLabel: "이름",
    emailLabel: "이메일",
    saveChangesBtn: "저장하기",
    profileUpdated: "개인정보가 변경되었습니다.",
    emailInUseError: "이미 사용 중인 이메일입니다.",
    guestProfileNotice: "게스트 상태에서는 개인정보를 변경할 수 없어요. 먼저 로그인해 주세요.",

    currentPasswordLabel: "현재 비밀번호",
    newPasswordLabel: "새 비밀번호",
    confirmPasswordLabel: "새 비밀번호 확인",
    changePasswordBtn: "비밀번호 변경",
    passwordChanged: "비밀번호가 변경되었습니다.",
    passwordMismatch: "새 비밀번호가 일치하지 않습니다.",
    passwordTooShort: "비밀번호는 8자 이상이어야 합니다.",
    noPasswordAccountNotice: "소셜/게스트 계정은 비밀번호가 없어 변경할 수 없어요.",

    notifyChatLabel: "채팅 알림",
    notifyChatSub: "기장에게 새 메시지가 오면 알려드려요",
    notifyDiaryLabel: "일기 알림",
    notifyDiarySub: "새 일기가 작성되면 알려드려요",
    notifyMarketingLabel: "마케팅 정보 수신",
    notifyMarketingSub: "이벤트 및 혜택 소식을 보내드려요",
    notificationsSaved: "알림 설정이 저장되었습니다.",
    guestNotifyNotice: "게스트 상태에서는 저장되지 않아요. 로그인 후 이용해 주세요.",

    noPaymentMethods: "등록된 결제 수단이 없어요.",
    addCardBtn: "카드 추가하기",
    cardNumberLabel: "카드 번호",
    cardNumberPlaceholder: "카드 번호를 입력하세요",
    cardAddedMsg: "카드가 등록되었습니다.",
    cardRemovedMsg: "카드가 삭제되었습니다.",
    invalidCardMsg: "유효하지 않은 카드 번호입니다.",
    removeCardBtn: "삭제",
    paymentSimNotice: "실제 결제는 이루어지지 않으며, 카드 전체 번호는 저장되지 않아요.",

    supportSub: "궁금한 점이나 불편한 점을 남겨주시면 확인 후 답변드릴게요.",
    categoryLabel: "문의 유형",
    categoryAccount: "계정",
    categoryBilling: "결제",
    categoryBug: "버그 신고",
    categoryContent: "콘텐츠",
    messageLabel: "문의 내용",
    messagePlaceholder: "궁금한 점을 자세히 적어주세요 (5자 이상)",
    submitTicketBtn: "문의 보내기",
    ticketSubmittedMsg: "문의가 접수되었습니다. 빠르게 확인할게요!",
    login: "로그인",
    logout: "로그아웃",
    withdrawAccount: "회원 탈퇴",
    withdrawModalTitle: "정말 탈퇴하시겠어요?",
    withdrawModalWarning: "탈퇴 시 학습 기록, 대화 기억, 일기, 단어장, 코인 등 모든 개인 데이터가 즉시 삭제되며 복구할 수 없습니다.",
    withdrawModalRetentionNotice: "단, 관련 법령에 따라 계정 식별 정보(이메일)는 5년간 보관 후 파기됩니다.",
    withdrawViewFullPolicy: "자세한 내용 보기",
    withdrawPasswordLabel: "비밀번호 확인",
    withdrawPasswordPlaceholder: "비밀번호를 입력하세요",
    withdrawConfirmBtn: "탈퇴하기",
    withdrawCancelBtn: "취소",
    withdrawSuccessMsg: "탈퇴가 완료되었습니다. 그동안 이용해 주셔서 감사합니다.",
    withdrawErrorWrongPassword: "비밀번호가 올바르지 않습니다",

    // Home / Map Page
    travel: "여행하기",
    selectDestination: "목적지를 선택하세요",
    whereToGo: "어디로 떠날까요?",
    mateAwaits: "목적지를 선택하면 메이트가 기다려요",
    openRegions: "개방 지역",
    visitedPlaces: "방문 장소",
    membership: "멤버십",
    boardingPass: "BOARDING PASS · 탑승권",
    visit: "방문",
    placesCount: "곳",
    daysStreak: "일 연속",
    premiumOnly: "프리미엄 전용",

    // Chat Page
    chatTitle: "대화하기",
    chatSub: "기장님과의 감성 한국어 대화",
    selectCaptain: "기장님을 선택하세요",
    selectCaptainSub: "각 노선 기장과 대화해보세요",
    captainBadge: "기장",
    routeLabel: "노선",
    startChat: "💬 대화 시작",
    lockedPremium: "🔒 잠금 (프리미엄)",

    // Routes
    seoulRoute: "서울·경기 노선",
    jeonjuRoute: "전주·전라 노선",
    busanRoute: "부산·경남 노선",
    chungcheongRoute: "충청·공주 노선",
    jejuRoute: "제주 노선",

    // Vocab Page
    vocabTitle: "단어장",
    vocabSub: "여행에서 배운 필수 한국어 단어",
    allWords: "전체 단어",
    masteredWords: "마스터한 단어",
    practiceVocab: "단어 퀴즈 연습",

    // Profile Page
    selectLang: "🌐 언어 설정 (Language Settings)",
    beginnerLearner: "초급 학습자",
    coins: "코인",
    learningStats: "학습 통계",
    learnedWords: "배운 단어",
    mastered: "마스터",
    wordStatusNew: "새 단어",
    wordStatusLearning: "학습 중",
    wordStatusReview: "복습 필요",
    diaries: "해금 일기",
    settings: "설정",
    langSettings: "🌐 언어 설정",

    // Learn & Exercises
    startLearn: "🚀 학습 시작!",
    nextChapter: "▶️ 다음 챕터 학습하기",
    backToList: "‹ 챕터 목록으로",
    listen: "🔊 들어보기",
    hint: "💡 힌트",
    skip: "⏭️ 스킵",
    checkAnswer: "정답 확인",
    nextQuestion: "다음 문제 →",
    nextWord: "다음 단어 →",
    practiceCompleteTitle: "복습 완료!",
    practiceCompleteSub: "단어 {n}개를 모두 복습했어요.",
    attemptNotice: "❌ 오답입니다! 다시 시도해 보세요.",
    correctNotice: "🎉 정답입니다!",

    // Learn Main Page
    learnTitle: "기장과 공부하기",
    tabRegional: "🗺️ 지역 문화",
    tabSpecial: "⭐ 스페셜 주제별",
    selectCaptainLearn: "👨‍✈️ 함께 공부할 남성 기장님 선택",
    romanceStory: "❤️ 로맨스 스토리 (10개)",
    dailyStory: "☕ 일상 스토리 (10개)",
    friendshipStory: "🤝 친구 스토리 (10개)",
    premiumSpecialMode: "⭐ 프리미엄 스페셜 모드",
    totalChapters: "챕터",
    chapterCount: "단계",
    progressLabel: "현재 진도",
    ongoing: "진행중",
    completed: "완료",
    locked: "잠김",
    chapterLockedHint: "이전 챕터를 먼저 완료해주세요",
    regionalChaptersLabel: "기장의 지역 문화 커리큘럼",

    // Diary Page
    diaryTitle: "일기",
    diarySub: "기장님과의 추억 일기장",
    diaryEmptyMsg: "아직 쓴 일기가 없어요. {name} 기장님과 대화를 나누면 일기가 쓰여요!",
    diaryEmptyBtn: "{name} 기장님과 대화하러 가기",
    tabAll: "전체",
    tabUnlocked: "해금",
    tabLocked: "잠금",
    unlockWithCoins: "코인으로 해금",
    unlockBtn: "해금하기",
    lockedStatus: "잠금",
    unlockedStatus: "해금됨",

    chooseMate: "메이트 선택",
    freeBadge: "✓ 무료",
    premiumBadge: "⭐ 프리미엄",
    chatBtn: "💬 대화하기",
    studyBtn: "📖 공부하기",
    diaryBtn: "📔 일기",
    premiumLockedBtn: "🔒 프리미엄 전용 (잠금)",
    premiumLockedTitle: "프리미엄 전용 챕터예요",
    premiumLockedSub: "구독 후 이 챕터를 학습할 수 있어요",
    regionHighlights: "이 지역 명소",
    placeGyeongbokgung: "Gyeongbokgung",
    placeHongdae: "Hongdae",
    placeNamsanTower: "Namsan Tower",
    placeHanokVillage: "Hanok Village",
    placeBibimbapStreet: "Bibimbap Street",
    placeGyeonggijeon: "Gyeonggijeon",
    placeHaeundae: "Haeundae Beach",
    placeJagalchiMarket: "Jagalchi Market",
    placeGwanganBridge: "Gwangan Bridge",
    placeMuryeongTomb: "King Muryeong's Tomb",
    placeGongsanseong: "Gongsanseong Fortress",
    placeGeumgangRiver: "Geumgang River",
    placeSeongsanIlchulbong: "Seongsan Ilchulbong",
    placeHallasan: "Hallasan",
    placeUdoIsland: "Udo Island",
    romanizationChip: "🔤 발음 그대로 (Romanization)",
    hintChip: "💡 힌트 보기",
    storySkip: "건너뛰기 ›",
    storyNext: "다음 ▾",
    storyGoToQuiz: "🚀 문제 풀러 가기!",
    todaysWords: "오늘의 단어",
    todaysWordsSub: "방금 읽은 이야기에 나온 단어들이에요. 눈에 익혀볼까요?",
    saveWordsAndQuiz: "단어장에 저장하고 문제 풀기 →",
    wordSavedToast: "'{word}' 단어장에 저장했어요!",
    sttNotSupportedToast: "이 브라우저에서는 음성 인식을 지원하지 않습니다.",
    sessionComplete: "학습 완료!",
    scoreLabel: "점수",
    correctLabel: "정답",
    wrongLabel: "오답",
    coinEarned: "코인 획득",
    backToChapterList: "📖 챕터 목록으로",
    chatWithCaptain: "💬 기장님과 대화하기",
    contentNotReadyTitle: "콘텐츠 준비 중이에요",
    contentNotReadySub: "아직 이 챕터의 콘텐츠가 준비되지 않았어요.",
    backToMap: "지도로 돌아가기",
    questionsLabel: "문제",
    chancesLabel: "기회",
    chancesCount: "3회",
    sessionTagline: "문화와 언어를 함께 배우는 인터랙티브 세션",
    loadingChapter: "랜딩중...",
    loadingChapterDone: "랜딩 완료!",
    attemptNoticeWithCount: "❌ 오답입니다! 다시 시도해 보세요. (남은 기회: {n}회)",
    checkAnswerWithCount: "정답 확인 (기회 {n}/3)",
    wrongFinalPrefix: "💡 3회 실패 — 정답:",
    speakingCorrect: "🎉 훌륭한 한국어 발음입니다!",
    hintShort: "힌트",
    hintCloseShort: "힌트 닫기",
    lockedTitle: "{name} 기장 학습 잠금",
    lockedDesc: "이 노선의 학습은 프리미엄 전용입니다. 구독 후 이용해 주세요.",
    backToMapWithArrow: "← 지도로 돌아가기",
    viewPremiumBtn: "⭐ 프리미엄 보기",
    startWithEmail: "✉️ 이메일로 계속하기",
    orDivider: "또는",
    continueGoogle: "Google로 계속하기",
    continueApple: "🍎 Apple로 계속하기",
    noAccountYet: "계정이 없으신가요?",
    signUp: "회원가입",
    startHere: "시작하기",
    continueWithAccount: "계정으로 계속하세요",
    monthlySub: "월간 구독",
    perMonth: "/월",
    cancelAnytime: "언제든지 해지 가능 · Cancel anytime",
    startPremiumBtn: "⭐ 프리미엄 시작하기",
    alreadyPremiumBtn: "✓ 이미 구독 중이에요",
    freeTrial: "7일 무료 체험 · 7-day free trial",
    perkAllMates: "모든 메이트 이용",
    perkAllDiaries: "모든 일기 해금 가능",
    perkAllChapters: "전체 챕터 학습",
    perkAllRegions: "모든 지역 탐방",
    perkCoinBonus: "코인 보너스 +50%",
    perkEarlyAccess: "신규 콘텐츠 우선 접근",
    laterBtn: "‹ 나중에",
    coinShopTitle: "코인 상점",
    coinPackSmallLabel: "코인 50개",
    coinPackMediumLabel: "코인 180개 (30개 보너스)",
    coinPackLargeLabel: "코인 500개 (100개 보너스)",
    coinShopIntro: "코인으로 일기·기장님 사진첩을 바로 잠금해제할 수 있어요",
    coinShopNotice: "결제는 앱스토어 정책에 따라 환불이 제한될 수 있어요",
    buyBtn: "구매",
    processingBtn: "처리 중...",
    paymentFailedMsg: "결제에 실패했습니다.",
    cannotOpenPaymentMsg: "결제창을 열 수 없습니다.",
    serverConnectFailedMsg: "서버에 연결할 수 없습니다.",
    mailboxTitle: "{name} 기장님 편지함",
    letterMailboxLinkTitle: "편지함",
    writeLetterBtn: "편지 쓰기",
    noLettersYet: "아직 주고받은 편지가 없어요",
    sentLetterLabel: "보낸 편지",
    replyFromLabel: "{name} 기장님의 답장",
    waitingReplyMsg: "답장을 준비하고 있어요",
    checkAfterMsg: "이후에 확인해보세요",
    composeLetterTitle: "{name} 기장님께 편지 쓰기",
    composeLetterSub: "답장은 내일 이 시간쯤 도착해요.",
    composeLetterPlaceholder: "오늘 있었던 일이나 하고 싶은 이야기를 편지로 적어보세요...",
    yourCoinsLabel: "보유 코인",
    cancelBtn: "취소",
    sendLetterBtn: "보내기",
    sendingBtn: "보내는 중...",
    letterSendFailedMsg: "편지를 보내지 못했습니다.",
    backToListBtn: "← 목록으로",
    endSessionBtn: "종료",
    diaryLockTitle: "{name} 기장 일기 잠금",
    galleryLockTitle: "{name} 기장 사진첩 잠금",
    lettersLockTitle: "{name} 기장 편지함 잠금",
    chatLockTitle: "{name} 기장 노선 잠금",
    chatLockSub: "이 노선은 프리미엄 전용입니다. 구독 후 대화를 이용하실 수 있습니다.",
    premiumLockSub: "이 콘텐츠는 프리미엄 전용입니다. 구독 또는 개별 잠금해제 후 이용하실 수 있습니다.",
    premiumActiveTitle: "프리미엄 이용중",
    premiumUpgradeTitle: "프리미엄으로 업그레이드",
    premiumActiveSub: "모든 메이트 · 전체 챕터 이용 가능",
    premiumUpgradeSub: "모든 메이트를 만나고 전체 챕터를 배워보세요",
    manageArrow: "관리 →",
    viewArrow: "보기 →",
    unlockJustOneIntro: "구독이 부담스럽다면, 기장님 한 분만 골라서",
    unlockedLabel: "✓ 해금됨",
    notNowBtn: "나중에",
    paywallTitle: "무료 대화를 다 사용했어요",
    paywallSub: "무료 회원은 대화를 10번까지 나눌 수 있어요. 프리미엄으로 업그레이드하면 {name} 기장님과 자유롭게 대화할 수 있어요.",
    freeRemainingMsg: "무료 대화 {n}번 남음",
    unlimitedChatLink: "프리미엄으로 무제한 대화하기",
  },
  en: {
    home: "Home",
    map: "Travel",
    learn: "Learn",
    chat: "Chat",
    vocab: "Vocab",
    me: "My Page",
    myPage: "My Page",
    mateRouteTitle: "Route with Captain {name}",
    changeMate: "Change ›",
    selectMateTitle: "Select Your Mate",
    selectMateSub: "Choose the captain you'd like to learn with.",
    mateTagline_kyuhyun: "The smooth-talking veteran captain of the Seoul & Gyeonggi route.",
    mateTagline_haneul: "The blunt but caring younger captain of the Jeonju & Jeolla route.",
    mateTagline_sunwoo: "The playful childhood-friend captain of the Busan & Gyeongnam route.",
    mateTagline_sangwoo: "The by-the-book, tower-loving captain of the Chungcheong & Gongju route.",
    mateTagline_yongwoo: "The tsundere, brotherly captain of the Jeju route.",
    loadingTakeoff: "Preparing for takeoff...",
    galleryTitle: "Gallery",
    galleryEmptyMsg: "No photos ready yet.",
    gallerySoftLockNotice: "Photos you unlock with coins are saved to your account.",

    settingsAccount: "Settings · Account",
    settingsGeneral: "Settings · General",
    settingsLegal: "Settings · Legal & Support",
    settingsOther: "Other",
    editProfile: "Edit Profile",
    paymentMethods: "Manage Payment Methods",
    securitySettings: "Security",
    notificationSettings: "Notifications",
    themeSettings: "Theme",
    themeSettingsSub: "Choose how the app looks.",
    themeLight: "Light Mode",
    themeLightSub: "Bright and clean",
    themeDark: "Dark Mode",
    themeDarkSub: "Easy on the eyes at night",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    customerSupport: "Customer Support",
    appVersion: "App Version",
    backToMyPage: "‹ Back to My Page",
    savingBtn: "Saving...",

    nameLabel: "Name",
    emailLabel: "Email",
    saveChangesBtn: "Save Changes",
    profileUpdated: "Your profile has been updated.",
    emailInUseError: "This email is already in use.",
    guestProfileNotice: "You need to log in before editing your profile.",

    currentPasswordLabel: "Current Password",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm New Password",
    changePasswordBtn: "Change Password",
    passwordChanged: "Your password has been changed.",
    passwordMismatch: "New passwords don't match.",
    passwordTooShort: "Password must be at least 8 characters.",
    noPasswordAccountNotice: "This account has no password (social/guest login), so it can't be changed here.",

    notifyChatLabel: "Chat Notifications",
    notifyChatSub: "Get notified about new messages from your captain",
    notifyDiaryLabel: "Diary Notifications",
    notifyDiarySub: "Get notified when a new diary entry is written",
    notifyMarketingLabel: "Marketing Updates",
    notifyMarketingSub: "Receive news about events and perks",
    notificationsSaved: "Your notification settings have been saved.",
    guestNotifyNotice: "Settings won't be saved as a guest. Please log in first.",

    noPaymentMethods: "No payment methods registered yet.",
    addCardBtn: "Add Card",
    cardNumberLabel: "Card Number",
    cardNumberPlaceholder: "Enter your card number",
    cardAddedMsg: "Card added successfully.",
    cardRemovedMsg: "Card removed.",
    invalidCardMsg: "Invalid card number.",
    removeCardBtn: "Remove",
    paymentSimNotice: "No real charge is made, and full card numbers are never stored.",

    supportSub: "Leave your question or issue and we'll get back to you.",
    categoryLabel: "Category",
    categoryAccount: "Account",
    categoryBilling: "Billing",
    categoryBug: "Bug Report",
    categoryContent: "Content",
    messageLabel: "Message",
    messagePlaceholder: "Describe your issue in detail (min. 5 characters)",
    submitTicketBtn: "Submit",
    ticketSubmittedMsg: "Your inquiry has been received. We'll get back to you soon!",
    login: "Login",
    logout: "Logout",
    withdrawAccount: "Delete Account",
    withdrawModalTitle: "Are you sure you want to leave?",
    withdrawModalWarning: "Deleting your account will immediately and permanently erase your learning progress, chat memories, diary entries, vocabulary, and coins. This cannot be undone.",
    withdrawModalRetentionNotice: "However, by law your account's identifying information (email) will be retained for 5 years before final deletion.",
    withdrawViewFullPolicy: "View full policy",
    withdrawPasswordLabel: "Confirm password",
    withdrawPasswordPlaceholder: "Enter your password",
    withdrawConfirmBtn: "Delete my account",
    withdrawCancelBtn: "Cancel",
    withdrawSuccessMsg: "Your account has been deleted. Thank you for using K-MATE.",
    withdrawErrorWrongPassword: "Incorrect password",

    travel: "Travel Korea",
    selectDestination: "Select your destination",
    whereToGo: "Where to fly?",
    mateAwaits: "Select a destination and your captain awaits",
    openRegions: "Open Regions",
    visitedPlaces: "Visited Places",
    membership: "Membership",
    boardingPass: "BOARDING PASS",
    visit: "Visited",
    placesCount: "Places",
    daysStreak: "day streak",
    premiumOnly: "Premium Only",

    chatTitle: "Chat",
    chatSub: "Talk with your captain",
    selectCaptain: "Choose your Captain",
    selectCaptainSub: "Talk freely with captains of each route",
    captainBadge: "Captain",
    routeLabel: "Route",
    startChat: "💬 Start Chat",
    lockedPremium: "🔒 Locked (Premium)",

    seoulRoute: "Seoul & Gyeonggi Route",
    jeonjuRoute: "Jeonju & Jeolla Route",
    busanRoute: "Busan & Gyeongnam Route",
    chungcheongRoute: "Chungcheong & Gongju Route",
    jejuRoute: "Jeju Island Route",

    vocabTitle: "Vocab",
    vocabSub: "Essential Korean Words",
    allWords: "All Words",
    masteredWords: "Mastered Words",
    practiceVocab: "Vocab Quiz",

    selectLang: "🌐 Language Settings",
    beginnerLearner: "Beginner Learner",
    coins: "Coins",
    learningStats: "Stats",
    learnedWords: "Words",
    mastered: "Mastered",
    wordStatusNew: "New",
    wordStatusLearning: "Learning",
    wordStatusReview: "Review Due",
    diaries: "Diaries",
    settings: "Settings",
    langSettings: "🌐 Language Settings",

    startLearn: "🚀 Start Learning!",
    nextChapter: "▶️ Next Chapter",
    backToList: "‹ Back to List",
    listen: "🔊 Listen",
    hint: "💡 Hint",
    skip: "⏭️ Skip",
    checkAnswer: "Check Answer",
    nextQuestion: "Next Question →",
    nextWord: "Next Word →",
    practiceCompleteTitle: "Review Complete!",
    practiceCompleteSub: "You reviewed all {n} words.",
    attemptNotice: "❌ Incorrect! Try again.",
    correctNotice: "🎉 Correct!",

    learnTitle: "Study with Captain",
    tabRegional: "🗺️ Regional Culture",
    tabSpecial: "⭐ Special Topics",
    selectCaptainLearn: "👨‍✈️ Choose Captain to Study With",
    romanceStory: "❤️ Romance (10)",
    dailyStory: "☕ Daily Life (10)",
    friendshipStory: "🤝 Friendship (10)",
    premiumSpecialMode: "⭐ Premium Special Mode",
    totalChapters: "Chapter",
    chapterCount: "Steps",
    progressLabel: "Progress",
    ongoing: "Ongoing",
    completed: "Done",
    locked: "Locked",
    chapterLockedHint: "Complete the previous chapter first",
    regionalChaptersLabel: "Regional Culture Curriculum",

    diaryTitle: "Diary",
    diarySub: "Memories with Captain",
    diaryEmptyMsg: "No diary entries yet. Chat with Captain {name} to write one!",
    diaryEmptyBtn: "Chat with Captain {name}",
    tabAll: "All",
    tabUnlocked: "Unlocked",
    tabLocked: "Locked",
    unlockWithCoins: "Unlock with coins",
    unlockBtn: "Unlock",
    lockedStatus: "Locked",
    unlockedStatus: "Unlocked",

    chooseMate: "Choose your mate",
    freeBadge: "✓ Free",
    premiumBadge: "⭐ Premium",
    chatBtn: "💬 Chat",
    studyBtn: "📖 Study",
    diaryBtn: "📔 Diary",
    premiumLockedBtn: "🔒 Premium Only (Locked)",
    premiumLockedTitle: "This chapter is premium-only",
    premiumLockedSub: "Subscribe to unlock this chapter",
    regionHighlights: "Highlights",
    placeGyeongbokgung: "Gyeongbokgung",
    placeHongdae: "Hongdae",
    placeNamsanTower: "Namsan Tower",
    placeHanokVillage: "Hanok Village",
    placeBibimbapStreet: "Bibimbap Street",
    placeGyeonggijeon: "Gyeonggijeon",
    placeHaeundae: "Haeundae Beach",
    placeJagalchiMarket: "Jagalchi Market",
    placeGwanganBridge: "Gwangan Bridge",
    placeMuryeongTomb: "King Muryeong's Tomb",
    placeGongsanseong: "Gongsanseong Fortress",
    placeGeumgangRiver: "Geumgang River",
    placeSeongsanIlchulbong: "Seongsan Ilchulbong",
    placeHallasan: "Hallasan",
    placeUdoIsland: "Udo Island",
    romanizationChip: "🔤 Romanization",
    hintChip: "💡 Show Hint",
    storySkip: "Skip ›",
    storyNext: "Next ▾",
    storyGoToQuiz: "🚀 Start the Quiz!",
    todaysWords: "Today's Words",
    todaysWordsSub: "Here are the words from the story you just read. Let's take a look.",
    saveWordsAndQuiz: "Save to Vocab & Start Quiz →",
    wordSavedToast: "'{word}' saved to vocab!",
    sttNotSupportedToast: "Speech recognition is not supported in this browser.",
    sessionComplete: "Session Complete!",
    scoreLabel: "Score",
    correctLabel: "Correct",
    wrongLabel: "Wrong",
    coinEarned: "Coins Earned",
    backToChapterList: "📖 Back to Chapters",
    chatWithCaptain: "💬 Chat with Captain",
    contentNotReadyTitle: "Content Coming Soon",
    contentNotReadySub: "This chapter's content isn't ready yet.",
    backToMap: "Back to Map",
    questionsLabel: "Questions",
    chancesLabel: "Chances",
    chancesCount: "3 tries",
    sessionTagline: "Interactive Culture & Language Session",
    loadingChapter: "Landing...",
    loadingChapterDone: "Landing complete!",
    attemptNoticeWithCount: "❌ Incorrect! Try again. ({n} tries left)",
    checkAnswerWithCount: "Check Answer ({n}/3 tries)",
    wrongFinalPrefix: "💡 3 attempts used — Answer:",
    speakingCorrect: "🎉 Excellent Korean pronunciation!",
    hintShort: "Hint",
    hintCloseShort: "Hide Hint",
    lockedTitle: "Captain {name}'s Lessons Locked",
    lockedDesc: "This route's lessons are premium only. Please subscribe to access.",
    backToMapWithArrow: "← Back to Map",
    viewPremiumBtn: "⭐ View Premium",
    startWithEmail: "✉️ Continue with Email",
    orDivider: "or",
    continueGoogle: "Continue with Google",
    continueApple: "🍎 Continue with Apple",
    noAccountYet: "Don't have an account?",
    signUp: "Sign Up",
    startHere: "Get Started",
    continueWithAccount: "Continue with your account",
    monthlySub: "Monthly Subscription",
    perMonth: "/mo",
    cancelAnytime: "Cancel anytime",
    startPremiumBtn: "⭐ Start Premium",
    alreadyPremiumBtn: "✓ Already Subscribed",
    freeTrial: "7-day free trial",
    perkAllMates: "Unlimited access to all mates",
    perkAllDiaries: "Unlock diaries from all mates",
    perkAllChapters: "Access all learning chapters",
    perkAllRegions: "Explore all 5 regions",
    perkCoinBonus: "50% bonus coins on all activities",
    perkEarlyAccess: "Early access to new content",
    laterBtn: "‹ Later",
    coinShopTitle: "Coin Shop",
    coinPackSmallLabel: "50 Coins",
    coinPackMediumLabel: "180 Coins (+30 bonus)",
    coinPackLargeLabel: "500 Coins (+100 bonus)",
    coinShopIntro: "Use coins to instantly unlock diaries and your captain's photo gallery",
    coinShopNotice: "Refunds may be limited according to app store policy",
    buyBtn: "Buy",
    processingBtn: "Processing...",
    paymentFailedMsg: "Payment failed.",
    cannotOpenPaymentMsg: "Couldn't open the payment window.",
    serverConnectFailedMsg: "Couldn't connect to the server.",
    mailboxTitle: "{name}'s Mailbox",
    letterMailboxLinkTitle: "Mailbox",
    writeLetterBtn: "Write a Letter",
    noLettersYet: "No letters exchanged yet",
    sentLetterLabel: "Sent Letter",
    replyFromLabel: "Reply from {name}",
    waitingReplyMsg: "Preparing a reply",
    checkAfterMsg: "Check back after",
    composeLetterTitle: "Write a letter to {name}",
    composeLetterSub: "The reply will arrive around this time tomorrow.",
    composeLetterPlaceholder: "Write about your day or anything you'd like to share...",
    yourCoinsLabel: "Your Coins",
    cancelBtn: "Cancel",
    sendLetterBtn: "Send",
    sendingBtn: "Sending...",
    letterSendFailedMsg: "Couldn't send the letter.",
    backToListBtn: "← Back to list",
    endSessionBtn: "End",
    diaryLockTitle: "{name}'s Diary is Locked",
    galleryLockTitle: "{name}'s Gallery is Locked",
    lettersLockTitle: "{name}'s Mailbox is Locked",
    chatLockTitle: "{name}'s Route is Locked",
    chatLockSub: "This route is premium only. Subscribe to start chatting.",
    premiumLockSub: "This content is premium only. Subscribe or unlock this captain individually to access it.",
    premiumActiveTitle: "Premium Active",
    premiumUpgradeTitle: "Upgrade to Premium",
    premiumActiveSub: "Access to all mates · all chapters",
    premiumUpgradeSub: "Meet every mate and learn all chapters",
    manageArrow: "Manage →",
    viewArrow: "View →",
    unlockJustOneIntro: "If a subscription feels like too much, unlock just one captain",
    unlockedLabel: "✓ Unlocked",
    notNowBtn: "Not now",
    paywallTitle: "You've used all your free messages",
    paywallSub: "Free members can chat up to 10 times. Upgrade to Premium to chat freely with Captain {name}.",
    freeRemainingMsg: "{n} free messages left",
    unlimitedChatLink: "Chat unlimited with Premium",
  },
  ru: {
    home: "Главная",
    map: "Путешествие",
    learn: "Обучение",
    chat: "Чат",
    vocab: "Словарь",
    me: "Профиль",
    myPage: "Моя страница",
    mateRouteTitle: "Маршрут с капитаном {name}",
    changeMate: "Сменить ›",
    selectMateTitle: "Выберите напарника",
    selectMateSub: "Выберите капитана, с которым хотите учиться.",
    mateTagline_kyuhyun: "Обаятельный опытный капитан маршрута Сеул–Кёнгидо.",
    mateTagline_haneul: "Немногословный, но заботливый младший капитан маршрута Чонджу–Чолла.",
    mateTagline_sunwoo: "Игривый капитан-друг детства маршрута Пусан–Кёнгнам.",
    mateTagline_sangwoo: "Строгий по уставу капитан-диспетчер маршрута Чхунчхон–Конджу.",
    mateTagline_yongwoo: "Капитан маршрута Чеджу, заботливый как старший брат — с виду ворчливый.",
    loadingTakeoff: "Готовимся к вылету...",
    galleryTitle: "Галерея",
    galleryEmptyMsg: "Пока нет готовых фото.",
    gallerySoftLockNotice: "Фото, открытые за монеты, сохраняются в вашем аккаунте.",

    settingsAccount: "Настройки · Аккаунт",
    settingsGeneral: "Настройки · Общие",
    settingsLegal: "Настройки · Правовая информация и поддержка",
    settingsOther: "Другое",
    editProfile: "Изменить профиль",
    paymentMethods: "Управление способами оплаты",
    securitySettings: "Безопасность",
    notificationSettings: "Уведомления",
    themeSettings: "Тема",
    themeSettingsSub: "Выберите оформление приложения.",
    themeLight: "Светлая тема",
    themeLightSub: "Яркий и чистый экран",
    themeDark: "Тёмная тема",
    themeDarkSub: "Комфортно для глаз ночью",
    termsOfService: "Условия использования",
    privacyPolicy: "Политика конфиденциальности",
    customerSupport: "Поддержка",
    appVersion: "Версия приложения",
    backToMyPage: "‹ Назад к моей странице",
    savingBtn: "Сохранение...",

    nameLabel: "Имя",
    emailLabel: "Эл. почта",
    saveChangesBtn: "Сохранить",
    profileUpdated: "Профиль обновлён.",
    emailInUseError: "Этот email уже используется.",
    guestProfileNotice: "Войдите в аккаунт, чтобы изменить профиль.",

    currentPasswordLabel: "Текущий пароль",
    newPasswordLabel: "Новый пароль",
    confirmPasswordLabel: "Подтвердите новый пароль",
    changePasswordBtn: "Изменить пароль",
    passwordChanged: "Пароль изменён.",
    passwordMismatch: "Новые пароли не совпадают.",
    passwordTooShort: "Пароль должен содержать минимум 8 символов.",
    noPasswordAccountNotice: "У этого аккаунта нет пароля (соц. сеть/гость), изменить его здесь нельзя.",

    notifyChatLabel: "Уведомления чата",
    notifyChatSub: "Получайте уведомления о новых сообщениях от капитана",
    notifyDiaryLabel: "Уведомления дневника",
    notifyDiarySub: "Получайте уведомления о новых записях в дневнике",
    notifyMarketingLabel: "Маркетинговые рассылки",
    notifyMarketingSub: "Новости об акциях и бонусах",
    notificationsSaved: "Настройки уведомлений сохранены.",
    guestNotifyNotice: "В гостевом режиме настройки не сохраняются. Сначала войдите в аккаунт.",

    noPaymentMethods: "Способы оплаты ещё не добавлены.",
    addCardBtn: "Добавить карту",
    cardNumberLabel: "Номер карты",
    cardNumberPlaceholder: "Введите номер карты",
    cardAddedMsg: "Карта добавлена.",
    cardRemovedMsg: "Карта удалена.",
    invalidCardMsg: "Недействительный номер карты.",
    removeCardBtn: "Удалить",
    paymentSimNotice: "Реальное списание не происходит, полный номер карты не сохраняется.",

    supportSub: "Опишите вопрос или проблему — мы ответим как можно скорее.",
    categoryLabel: "Категория",
    categoryAccount: "Аккаунт",
    categoryBilling: "Оплата",
    categoryBug: "Сообщить об ошибке",
    categoryContent: "Контент",
    messageLabel: "Сообщение",
    messagePlaceholder: "Опишите проблему подробнее (мин. 5 символов)",
    submitTicketBtn: "Отправить",
    ticketSubmittedMsg: "Ваш запрос получен. Мы скоро ответим!",
    login: "Войти",
    logout: "Выйти",
    withdrawAccount: "Удалить аккаунт",
    withdrawModalTitle: "Вы уверены, что хотите уйти?",
    withdrawModalWarning: "При удалении аккаунта ваш прогресс обучения, история чатов, дневник, словарь и монеты будут немедленно и безвозвратно удалены.",
    withdrawModalRetentionNotice: "Однако по закону идентифицирующая информация об аккаунте (email) будет храниться 5 лет перед окончательным удалением.",
    withdrawViewFullPolicy: "Подробнее",
    withdrawPasswordLabel: "Подтвердите пароль",
    withdrawPasswordPlaceholder: "Введите пароль",
    withdrawConfirmBtn: "Удалить аккаунт",
    withdrawCancelBtn: "Отмена",
    withdrawSuccessMsg: "Ваш аккаунт удалён. Спасибо, что пользовались K-MATE.",
    withdrawErrorWrongPassword: "Неверный пароль",

    travel: "Путешествие по Корее",
    selectDestination: "Выберите направление",
    whereToGo: "Куда отправимся?",
    mateAwaits: "Выберите направление, и капитан будет ждать вас",
    openRegions: "Открытые регионы",
    visitedPlaces: "Посещенные места",
    membership: "Членство",
    boardingPass: "ПОСАДОЧНЫЙ ТАЛОН",
    visit: "Визитов",
    placesCount: "Мест",
    daysStreak: "дней подряд",
    premiumOnly: "Только Премиум",

    chatTitle: "Чат",
    chatSub: "Общение с капитаном",
    selectCaptain: "Выберите капитана",
    selectCaptainSub: "Общайтесь с капитанами рейсов",
    captainBadge: "Капитан",
    routeLabel: "Рейс",
    startChat: "💬 Начать чат",
    lockedPremium: "🔒 Заблокировано (Премиум)",

    seoulRoute: "Рейс Сеул и Кёнги",
    jeonjuRoute: "Рейс Чонджу и Чолла",
    busanRoute: "Рейс Пусан и Кённам",
    chungcheongRoute: "Рейс Чхунчхон и Гонджу",
    jejuRoute: "Рейс о. Чеджу",

    vocabTitle: "Словарь",
    vocabSub: "Корейские слова",
    allWords: "Все слова",
    masteredWords: "Изученные слова",
    practiceVocab: "Викторина слов",

    selectLang: "🌐 Настройки языка",
    beginnerLearner: "Начинающий",
    coins: "Монеты",
    learningStats: "Статистика",
    learnedWords: "Слова",
    mastered: "Изучено",
    wordStatusNew: "Новое слово",
    wordStatusLearning: "Изучается",
    wordStatusReview: "Нужно повторить",
    diaries: "Дневники",
    settings: "Настройки",
    langSettings: "🌐 Настройки языка",

    startLearn: "🚀 Начать обучение!",
    nextChapter: "▶️ Следующая глава",
    backToList: "‹ К списку глав",
    listen: "🔊 Слушать",
    hint: "💡 Подсказка",
    skip: "⏭️ Пропустить",
    checkAnswer: "Проверить ответ",
    nextQuestion: "Следующий вопрос →",
    nextWord: "Следующее слово →",
    practiceCompleteTitle: "Повторение завершено!",
    practiceCompleteSub: "Вы повторили все {n} слов.",
    attemptNotice: "❌ Неверно! Попробуйте еще раз.",
    correctNotice: "🎉 Верно!",

    learnTitle: "Учеба с капитаном",
    tabRegional: "🗺️ Культура (10 глав)",
    tabSpecial: "⭐ Специальные темы (30 глав)",
    selectCaptainLearn: "👨‍✈️ Выберите капитана для обучения",
    romanceStory: "❤️ Романтика (10)",
    dailyStory: "☕ Повседневность (10)",
    friendshipStory: "🤝 Дружба (10)",
    premiumSpecialMode: "⭐ Премиум спец-режим",
    totalChapters: "Глава",
    chapterCount: "Шагов",
    progressLabel: "Прогресс",
    ongoing: "В процессе",
    completed: "Готово",
    locked: "Закрыто",
    chapterLockedHint: "Сначала завершите предыдущую главу",
    regionalChaptersLabel: "Курс региональной культуры",

    diaryTitle: "Дневник",
    diarySub: "Воспоминания с капитаном",
    diaryEmptyMsg: "Записей пока нет. Поговорите с капитаном {name}, чтобы появилась запись!",
    diaryEmptyBtn: "Поговорить с капитаном {name}",
    tabAll: "Все",
    tabUnlocked: "Открытые",
    tabLocked: "Заблокированные",
    unlockWithCoins: "Разблокировать за монеты",
    unlockBtn: "Разблокировать",
    lockedStatus: "Заблокировано",
    unlockedStatus: "Открыто",

    chooseMate: "Выберите напарника",
    freeBadge: "✓ Бесплатно",
    premiumBadge: "⭐ Премиум",
    chatBtn: "💬 Чат",
    studyBtn: "📖 Учиться",
    diaryBtn: "📔 Дневник",
    premiumLockedBtn: "🔒 Только Премиум (Заблокировано)",
    premiumLockedTitle: "Эта глава только для Премиум",
    premiumLockedSub: "Оформите подписку, чтобы открыть эту главу",
    regionHighlights: "Достопримечательности",
    placeGyeongbokgung: "Кёнбоккун",
    placeHongdae: "Хондэ",
    placeNamsanTower: "Башня Намсан",
    placeHanokVillage: "Деревня Ханок",
    placeBibimbapStreet: "Улица Бибимбап",
    placeGyeonggijeon: "Кёнгиджон",
    placeHaeundae: "Пляж Хэундэ",
    placeJagalchiMarket: "Рынок Чагальчхи",
    placeGwanganBridge: "Мост Кванан",
    placeMuryeongTomb: "Гробница короля Мурёна",
    placeGongsanseong: "Крепость Консансон",
    placeGeumgangRiver: "Река Кымган",
    placeSeongsanIlchulbong: "Сонсан Ильчхульбон",
    placeHallasan: "Халласан",
    placeUdoIsland: "Остров Удо",
    romanizationChip: "🔤 Транслитерация",
    hintChip: "💡 Показать подсказку",
    storySkip: "Пропустить ›",
    storyNext: "Далее ▾",
    storyGoToQuiz: "🚀 Начать викторину!",
    todaysWords: "Слова сегодняшнего дня",
    todaysWordsSub: "Вот слова из истории, которую вы только что прочитали.",
    saveWordsAndQuiz: "Сохранить слова и начать викторину →",
    wordSavedToast: "'{word}' сохранено в словарь!",
    sttNotSupportedToast: "Распознавание речи не поддерживается в этом браузере.",
    sessionComplete: "Урок завершен!",
    scoreLabel: "Очки",
    correctLabel: "Правильно",
    wrongLabel: "Неправильно",
    coinEarned: "Монет получено",
    backToChapterList: "📖 К списку глав",
    chatWithCaptain: "💬 Чат с капитаном",
    contentNotReadyTitle: "Контент скоро появится",
    contentNotReadySub: "Содержание этой главы еще не готово.",
    backToMap: "Вернуться к карте",
    questionsLabel: "Вопросы",
    chancesLabel: "Попытки",
    chancesCount: "3 попытки",
    sessionTagline: "Интерактивный урок культуры и языка",
    loadingChapter: "Посадка...",
    loadingChapterDone: "Посадка завершена!",
    attemptNoticeWithCount: "❌ Неверно! Попробуйте еще раз. (Осталось попыток: {n})",
    checkAnswerWithCount: "Проверить ответ (попытка {n}/3)",
    wrongFinalPrefix: "💡 3 неудачные попытки — Ответ:",
    speakingCorrect: "🎉 Отличное произношение корейского!",
    hintShort: "Подсказка",
    hintCloseShort: "Скрыть подсказку",
    lockedTitle: "Уроки капитана {name} заблокированы",
    lockedDesc: "Уроки этого маршрута доступны только по подписке Премиум.",
    backToMapWithArrow: "← Вернуться к карте",
    viewPremiumBtn: "⭐ Смотреть Премиум",
    startWithEmail: "✉️ Продолжить с Email",
    orDivider: "или",
    continueGoogle: "Продолжить с Google",
    continueApple: "🍎 Продолжить с Apple",
    noAccountYet: "Нет аккаунта?",
    signUp: "Регистрация",
    startHere: "Начать",
    continueWithAccount: "Продолжите с аккаунтом",
    monthlySub: "Ежемесячная подписка",
    perMonth: "/мес",
    cancelAnytime: "Отмена в любое время",
    startPremiumBtn: "⭐ Начать Премиум",
    alreadyPremiumBtn: "✓ Вы уже подписаны",
    freeTrial: "7 дней бесплатно",
    perkAllMates: "Безлимитный доступ ко всем мейтам",
    perkAllDiaries: "Открывайте дневники всех мейтов",
    perkAllChapters: "Доступ ко всем главам обучения",
    perkAllRegions: "Исследуйте все 5 регионов",
    perkCoinBonus: "+50% бонусных монет за все активности",
    perkEarlyAccess: "Ранний доступ к новому контенту",
    laterBtn: "‹ Позже",
    coinShopTitle: "Магазин монет",
    coinPackSmallLabel: "50 монет",
    coinPackMediumLabel: "180 монет (+30 бонус)",
    coinPackLargeLabel: "500 монет (+100 бонус)",
    coinShopIntro: "Используйте монеты, чтобы сразу открыть дневники и фотоальбом капитана",
    coinShopNotice: "Возврат средств может быть ограничен согласно правилам магазина приложений",
    buyBtn: "Купить",
    processingBtn: "Обработка...",
    paymentFailedMsg: "Оплата не удалась.",
    cannotOpenPaymentMsg: "Не удалось открыть окно оплаты.",
    serverConnectFailedMsg: "Не удалось подключиться к серверу.",
    mailboxTitle: "Почта капитана {name}",
    letterMailboxLinkTitle: "Почта",
    writeLetterBtn: "Написать письмо",
    noLettersYet: "Писем пока нет",
    sentLetterLabel: "Отправленное письмо",
    replyFromLabel: "Ответ от {name}",
    waitingReplyMsg: "Готовит ответ",
    checkAfterMsg: "Проверьте после",
    composeLetterTitle: "Написать письмо капитану {name}",
    composeLetterSub: "Ответ придёт примерно в это же время завтра.",
    composeLetterPlaceholder: "Напишите о своём дне или о том, чем хотите поделиться...",
    yourCoinsLabel: "Ваши монеты",
    cancelBtn: "Отмена",
    sendLetterBtn: "Отправить",
    sendingBtn: "Отправка...",
    letterSendFailedMsg: "Не удалось отправить письмо.",
    backToListBtn: "← Назад к списку",
    endSessionBtn: "Завершить",
    diaryLockTitle: "Дневник {name} заблокирован",
    galleryLockTitle: "Галерея {name} заблокирована",
    lettersLockTitle: "Почта {name} заблокирована",
    chatLockTitle: "Маршрут {name} заблокирован",
    chatLockSub: "Этот маршрут доступен только по подписке. Оформите подписку, чтобы начать общение.",
    premiumLockSub: "Этот контент доступен только по подписке. Оформите подписку или разблокируйте этого капитана отдельно.",
    premiumActiveTitle: "Премиум активен",
    premiumUpgradeTitle: "Перейти на Премиум",
    premiumActiveSub: "Доступ ко всем мейтам и главам",
    premiumUpgradeSub: "Знакомьтесь со всеми мейтами и изучайте все главы",
    manageArrow: "Управление →",
    viewArrow: "Смотреть →",
    unlockJustOneIntro: "Если подписка — это слишком, разблокируйте только одного капитана",
    unlockedLabel: "✓ Разблокировано",
    notNowBtn: "Не сейчас",
    paywallTitle: "Бесплатные сообщения закончились",
    paywallSub: "Бесплатные участники могут общаться до 10 раз. Перейдите на Премиум, чтобы свободно общаться с капитаном {name}.",
    freeRemainingMsg: "Осталось {n} бесплатных сообщений",
    unlimitedChatLink: "Безлимитный чат с Премиум",
  },
  zh: {
    home: "首页",
    map: "旅游",
    learn: "学习",
    chat: "对话",
    vocab: "生词本",
    me: "个人中心",
    myPage: "个人中心",
    mateRouteTitle: "与{name}机长的航线",
    changeMate: "更换 ›",
    selectMateTitle: "选择你的搭档",
    selectMateSub: "请选择要一起学习的机长。",
    mateTagline_kyuhyun: "负责首尔·京畿航线的圆滑体贴的资深机长",
    mateTagline_haneul: "负责全州·全罗航线的高冷却又体贴的年下机长",
    mateTagline_sunwoo: "负责釜山·庆南航线的爱开玩笑的青梅竹马机长",
    mateTagline_sangwoo: "负责忠清·公州航线的一丝不苟的管制机长",
    mateTagline_yongwoo: "负责济州航线的傲娇型兄长般机长",
    loadingTakeoff: "正在准备起飞...",
    galleryTitle: "相册",
    galleryEmptyMsg: "还没有准备好的照片。",
    gallerySoftLockNotice: "用金币解锁的照片会保存在您的账户中。",

    settingsAccount: "设置 · 账户",
    settingsGeneral: "设置 · 通用",
    settingsLegal: "设置 · 法律与支持",
    settingsOther: "其他",
    editProfile: "修改个人信息",
    paymentMethods: "管理支付方式",
    securitySettings: "安全设置",
    notificationSettings: "通知设置",
    themeSettings: "主题设置",
    themeSettingsSub: "请选择应用的外观主题。",
    themeLight: "浅色模式",
    themeLightSub: "明亮清爽的画面",
    themeDark: "深色模式",
    themeDarkSub: "夜间使用更护眼",
    termsOfService: "使用条款",
    privacyPolicy: "隐私政策",
    customerSupport: "客户支持",
    appVersion: "应用版本",
    backToMyPage: "‹ 返回个人中心",
    savingBtn: "保存中...",

    nameLabel: "姓名",
    emailLabel: "邮箱",
    saveChangesBtn: "保存",
    profileUpdated: "个人信息已更新。",
    emailInUseError: "该邮箱已被使用。",
    guestProfileNotice: "访客状态下无法修改个人信息，请先登录。",

    currentPasswordLabel: "当前密码",
    newPasswordLabel: "新密码",
    confirmPasswordLabel: "确认新密码",
    changePasswordBtn: "修改密码",
    passwordChanged: "密码已修改。",
    passwordMismatch: "新密码不一致。",
    passwordTooShort: "密码至少需要8个字符。",
    noPasswordAccountNotice: "该账户（社交/访客登录）没有密码，无法在此修改。",

    notifyChatLabel: "聊天通知",
    notifyChatSub: "机长发来新消息时通知我",
    notifyDiaryLabel: "日记通知",
    notifyDiarySub: "有新日记时通知我",
    notifyMarketingLabel: "接收营销信息",
    notifyMarketingSub: "接收活动及优惠资讯",
    notificationsSaved: "通知设置已保存。",
    guestNotifyNotice: "访客状态下设置不会被保存，请先登录。",

    noPaymentMethods: "尚未添加任何支付方式。",
    addCardBtn: "添加卡片",
    cardNumberLabel: "卡号",
    cardNumberPlaceholder: "请输入卡号",
    cardAddedMsg: "卡片已添加。",
    cardRemovedMsg: "卡片已删除。",
    invalidCardMsg: "无效的卡号。",
    removeCardBtn: "删除",
    paymentSimNotice: "不会产生实际扣款，完整卡号也不会被保存。",

    supportSub: "请留下您的问题或困扰，我们确认后会尽快回复。",
    categoryLabel: "咨询类型",
    categoryAccount: "账户",
    categoryBilling: "支付",
    categoryBug: "错误反馈",
    categoryContent: "内容",
    messageLabel: "咨询内容",
    messagePlaceholder: "请详细描述您的问题（至少5个字符）",
    submitTicketBtn: "提交咨询",
    ticketSubmittedMsg: "咨询已提交，我们会尽快确认！",
    login: "登录",
    logout: "退出登录",
    withdrawAccount: "注销账户",
    withdrawModalTitle: "确定要离开吗？",
    withdrawModalWarning: "注销账户后，您的学习进度、聊天记忆、日记、单词本和金币将立即永久删除，无法恢复。",
    withdrawModalRetentionNotice: "但根据法律规定，账户识别信息（邮箱）将保留5年后才会彻底删除。",
    withdrawViewFullPolicy: "查看详情",
    withdrawPasswordLabel: "确认密码",
    withdrawPasswordPlaceholder: "请输入密码",
    withdrawConfirmBtn: "注销账户",
    withdrawCancelBtn: "取消",
    withdrawSuccessMsg: "账户已注销。感谢您使用 K-MATE。",
    withdrawErrorWrongPassword: "密码不正确",

    travel: "韩国旅游",
    selectDestination: "请选择目的地",
    whereToGo: "想去哪里？",
    mateAwaits: "选择目的地，机长将等待您",
    openRegions: "开放区域",
    visitedPlaces: "打卡地点",
    membership: "会员等级",
    boardingPass: "登机牌 · BOARDING PASS",
    visit: "已打卡",
    placesCount: "处",
    daysStreak: "天连续",
    premiumOnly: "高级会员专属",

    chatTitle: "对话",
    chatSub: "与机长感情韩语对话",
    selectCaptain: "请选择机长",
    selectCaptainSub: "与各航线机长自由对话",
    captainBadge: "机长",
    routeLabel: "航线",
    startChat: "💬 开始对话",
    lockedPremium: "🔒 未解锁 (高级会员)",

    seoulRoute: "首尔·京畿 航线",
    jeonjuRoute: "全州·全罗 航线",
    busanRoute: "釜山·庆南 航线",
    chungcheongRoute: "忠清·公州 航线",
    jejuRoute: "济州岛 航线",

    vocabTitle: "生词本",
    vocabSub: "学习到的韩语单词",
    allWords: "全部单词",
    masteredWords: "已掌握单词",
    practiceVocab: "单词测验",

    selectLang: "🌐 语言设置",
    beginnerLearner: "初级学习者",
    coins: "金币",
    learningStats: "学习统计",
    learnedWords: "已学单词",
    mastered: "已掌握",
    wordStatusNew: "新单词",
    wordStatusLearning: "学习中",
    wordStatusReview: "需要复习",
    diaries: "解锁日记",
    settings: "设置",
    langSettings: "🌐 语言设置",

    startLearn: "🚀 开始学习！",
    nextChapter: "▶️ 下一章学习",
    backToList: "‹ 返回章节列表",
    listen: "🔊 试听",
    hint: "💡 提示",
    skip: "⏭️ 跳过",
    checkAnswer: "核对答案",
    nextQuestion: "下一题 →",
    nextWord: "下一个单词 →",
    practiceCompleteTitle: "复习完成！",
    practiceCompleteSub: "已复习全部 {n} 个单词。",
    attemptNotice: "❌ 回答错误！请再试一次。",
    correctNotice: "🎉 回答正确！",

    learnTitle: "与机长一起学习",
    tabRegional: "🗺️ 地区文化 (10个章节)",
    tabSpecial: "⭐ 特别主题 (30个章节)",
    selectCaptainLearn: "👨‍✈️ 选择一起学习的机长",
    romanceStory: "❤️ 恋爱故事 (10个)",
    dailyStory: "☕ 日常生活 (10个)",
    friendshipStory: "🤝 友情故事 (10个)",
    premiumSpecialMode: "⭐ 高级会员专属特辑",
    totalChapters: "章节",
    chapterCount: "关卡",
    progressLabel: "当前进度",
    ongoing: "进行中",
    completed: "已完成",
    locked: "未解锁",
    chapterLockedHint: "请先完成上一章节",
    regionalChaptersLabel: "地区文化课程",

    diaryTitle: "日记",
    diarySub: "与机长的回忆日记",
    diaryEmptyMsg: "还没有日记。和{name}机长聊天就会写日记哦！",
    diaryEmptyBtn: "去和{name}机长聊天",
    tabAll: "全部",
    tabUnlocked: "已解锁",
    tabLocked: "未解锁",
    unlockWithCoins: "用金币解锁",
    unlockBtn: "解锁",
    lockedStatus: "未解锁",
    unlockedStatus: "已解锁",

    chooseMate: "选择伙伴",
    freeBadge: "✓ 免费",
    premiumBadge: "⭐ 高级会员",
    chatBtn: "💬 聊天",
    studyBtn: "📖 学习",
    diaryBtn: "📔 日记",
    premiumLockedBtn: "🔒 仅限高级会员（已锁定）",
    premiumLockedTitle: "这是高级会员专属章节",
    premiumLockedSub: "订阅后即可学习这一章节",
    regionHighlights: "景点",
    placeGyeongbokgung: "景福宫",
    placeHongdae: "弘大",
    placeNamsanTower: "南山塔",
    placeHanokVillage: "韩屋村",
    placeBibimbapStreet: "拌饭街",
    placeGyeonggijeon: "庆基殿",
    placeHaeundae: "海云台海滩",
    placeJagalchiMarket: "札嘎其市场",
    placeGwanganBridge: "广安大桥",
    placeMuryeongTomb: "武宁王陵",
    placeGongsanseong: "公山城",
    placeGeumgangRiver: "锦江",
    placeSeongsanIlchulbong: "城山日出峰",
    placeHallasan: "汉拿山",
    placeUdoIsland: "牛岛",
    romanizationChip: "🔤 罗马拼音",
    hintChip: "💡 显示提示",
    storySkip: "跳过 ›",
    storyNext: "下一步 ▾",
    storyGoToQuiz: "🚀 开始答题！",
    todaysWords: "今日单词",
    todaysWordsSub: "这些是刚才故事里出现的单词，一起来看看吧。",
    saveWordsAndQuiz: "保存到单词本并开始答题 →",
    wordSavedToast: "已将「{word}」保存到单词本！",
    sttNotSupportedToast: "此浏览器不支持语音识别。",
    sessionComplete: "学习完成！",
    scoreLabel: "得分",
    correctLabel: "正确",
    wrongLabel: "错误",
    coinEarned: "获得金币",
    backToChapterList: "📖 返回章节列表",
    chatWithCaptain: "💬 与机长聊天",
    contentNotReadyTitle: "内容即将上线",
    contentNotReadySub: "此章节的内容尚未准备好。",
    backToMap: "返回地图",
    questionsLabel: "题目",
    chancesLabel: "机会",
    chancesCount: "3次",
    sessionTagline: "互动式文化与语言学习课程",
    loadingChapter: "着陆中...",
    loadingChapterDone: "着陆完成!",
    attemptNoticeWithCount: "❌ 回答错误！请再试一次。（剩余机会：{n}次）",
    checkAnswerWithCount: "核对答案（机会 {n}/3）",
    wrongFinalPrefix: "💡 3次尝试失败 — 正确答案：",
    speakingCorrect: "🎉 韩语发音非常棒！",
    hintShort: "提示",
    hintCloseShort: "关闭提示",
    lockedTitle: "{name}机长的课程已锁定",
    lockedDesc: "该航线的学习内容仅限高级会员使用，请订阅后使用。",
    backToMapWithArrow: "← 返回地图",
    viewPremiumBtn: "⭐ 查看高级会员",
    startWithEmail: "✉️ 使用邮箱继续",
    orDivider: "或",
    continueGoogle: "使用Google继续",
    continueApple: "🍎 使用Apple继续",
    noAccountYet: "还没有账号？",
    signUp: "注册",
    startHere: "开始使用",
    continueWithAccount: "使用账号继续",
    monthlySub: "月度订阅",
    perMonth: "/月",
    cancelAnytime: "随时可取消",
    startPremiumBtn: "⭐ 开通高级会员",
    alreadyPremiumBtn: "✓ 已订阅",
    freeTrial: "7天免费试用",
    perkAllMates: "无限畅玩所有搭档",
    perkAllDiaries: "解锁所有搭档的日记",
    perkAllChapters: "学习全部章节",
    perkAllRegions: "探索全部5个地区",
    perkCoinBonus: "所有活动金币奖励+50%",
    perkEarlyAccess: "优先体验新内容",
    laterBtn: "‹ 稍后",
    coinShopTitle: "金币商店",
    coinPackSmallLabel: "50金币",
    coinPackMediumLabel: "180金币（赠30）",
    coinPackLargeLabel: "500金币（赠100）",
    coinShopIntro: "用金币立即解锁日记和机长的照片墙",
    coinShopNotice: "退款可能会根据应用商店政策受到限制",
    buyBtn: "购买",
    processingBtn: "处理中...",
    paymentFailedMsg: "支付失败。",
    cannotOpenPaymentMsg: "无法打开支付窗口。",
    serverConnectFailedMsg: "无法连接服务器。",
    mailboxTitle: "{name}机长的信箱",
    letterMailboxLinkTitle: "信箱",
    writeLetterBtn: "写信",
    noLettersYet: "还没有往来的信件",
    sentLetterLabel: "已发送的信",
    replyFromLabel: "{name}机长的回信",
    waitingReplyMsg: "正在准备回信",
    checkAfterMsg: "之后请查看",
    composeLetterTitle: "给{name}机长写信",
    composeLetterSub: "回信将在明天这个时间左右送达。",
    composeLetterPlaceholder: "写下今天发生的事或想说的话...",
    yourCoinsLabel: "持有金币",
    cancelBtn: "取消",
    sendLetterBtn: "发送",
    sendingBtn: "发送中...",
    letterSendFailedMsg: "信件发送失败。",
    backToListBtn: "← 返回列表",
    endSessionBtn: "结束",
    diaryLockTitle: "{name}机长的日记已锁定",
    galleryLockTitle: "{name}机长的相册已锁定",
    lettersLockTitle: "{name}机长的信箱已锁定",
    chatLockTitle: "{name}机长的航线已锁定",
    chatLockSub: "此航线仅限高级会员使用。订阅后即可开始对话。",
    premiumLockSub: "此内容仅限高级会员使用。订阅或单独解锁该机长后即可使用。",
    premiumActiveTitle: "高级会员使用中",
    premiumUpgradeTitle: "升级为高级会员",
    premiumActiveSub: "可使用所有搭档·全部章节",
    premiumUpgradeSub: "认识所有搭档，学习全部章节",
    manageArrow: "管理 →",
    viewArrow: "查看 →",
    unlockJustOneIntro: "如果订阅负担较大，可以只选一位机长解锁",
    unlockedLabel: "✓ 已解锁",
    notNowBtn: "以后再说",
    paywallTitle: "免费对话次数已用完",
    paywallSub: "免费会员最多可对话10次。升级为高级会员即可与{name}机长自由对话。",
    freeRemainingMsg: "剩余{n}次免费对话",
    unlimitedChatLink: "升级高级会员畅聊无限",
  },
  ja: {
    home: "ホーム",
    map: "旅行",
    learn: "学習",
    chat: "チャット",
    vocab: "単語帳",
    me: "マイページ",
    myPage: "マイページ",
    mateRouteTitle: "{name}機長との航路",
    changeMate: "変更 ›",
    selectMateTitle: "メイトを選択",
    selectMateSub: "一緒に学ぶ機長を選んでください。",
    mateTagline_kyuhyun: "ソウル・京畿路線を担当する、優しく色気のあるベテラン機長",
    mateTagline_haneul: "全州・全羅路線を担当する、素っ気ないけど優しい年下機長",
    mateTagline_sunwoo: "釜山・慶南路線を担当する、いたずら好きな幼なじみ機長",
    mateTagline_sangwoo: "忠清・公州路線を担当する、生真面目な管制官気質の機長",
    mateTagline_yongwoo: "済州路線を担当する、兄貴のようなツンデレ機長",
    loadingTakeoff: "出発の準備をしています...",
    galleryTitle: "フォトアルバム",
    galleryEmptyMsg: "まだ用意された写真がありません。",
    gallerySoftLockNotice: "コインで解除した写真はアカウントに保存されます。",

    settingsAccount: "設定 · アカウント",
    settingsGeneral: "設定 · 一般",
    settingsLegal: "設定 · 法律・サポート",
    settingsOther: "その他",
    editProfile: "個人情報の変更",
    paymentMethods: "支払い方法の管理",
    securitySettings: "セキュリティ設定",
    notificationSettings: "通知設定",
    themeSettings: "テーマ設定",
    themeSettingsSub: "画面のテーマを選択してください。",
    themeLight: "ライトモード",
    themeLightSub: "明るくすっきりした画面",
    themeDark: "ダークモード",
    themeDarkSub: "夜間でも目に優しい画面",
    termsOfService: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    customerSupport: "カスタマーサポート",
    appVersion: "アプリバージョン",
    backToMyPage: "‹ マイページに戻る",
    savingBtn: "保存中...",

    nameLabel: "名前",
    emailLabel: "メールアドレス",
    saveChangesBtn: "保存する",
    profileUpdated: "個人情報が変更されました。",
    emailInUseError: "すでに使用されているメールアドレスです。",
    guestProfileNotice: "ゲスト状態では個人情報を変更できません。先にログインしてください。",

    currentPasswordLabel: "現在のパスワード",
    newPasswordLabel: "新しいパスワード",
    confirmPasswordLabel: "新しいパスワード（確認）",
    changePasswordBtn: "パスワードを変更",
    passwordChanged: "パスワードが変更されました。",
    passwordMismatch: "新しいパスワードが一致しません。",
    passwordTooShort: "パスワードは8文字以上にしてください。",
    noPasswordAccountNotice: "このアカウント（SNS・ゲスト）はパスワードがないため、ここでは変更できません。",

    notifyChatLabel: "チャット通知",
    notifyChatSub: "機長から新しいメッセージが届いたらお知らせします",
    notifyDiaryLabel: "日記通知",
    notifyDiarySub: "新しい日記が書かれたらお知らせします",
    notifyMarketingLabel: "マーケティング情報の受信",
    notifyMarketingSub: "イベントや特典のお知らせをお送りします",
    notificationsSaved: "通知設定が保存されました。",
    guestNotifyNotice: "ゲスト状態では設定が保存されません。先にログインしてください。",

    noPaymentMethods: "登録された支払い方法がありません。",
    addCardBtn: "カードを追加",
    cardNumberLabel: "カード番号",
    cardNumberPlaceholder: "カード番号を入力してください",
    cardAddedMsg: "カードが登録されました。",
    cardRemovedMsg: "カードが削除されました。",
    invalidCardMsg: "無効なカード番号です。",
    removeCardBtn: "削除",
    paymentSimNotice: "実際の決済は行われず、カード番号全体も保存されません。",

    supportSub: "ご質問やお困りごとを残していただければ、確認のうえご返信します。",
    categoryLabel: "お問い合わせ種別",
    categoryAccount: "アカウント",
    categoryBilling: "決済",
    categoryBug: "不具合報告",
    categoryContent: "コンテンツ",
    messageLabel: "お問い合わせ内容",
    messagePlaceholder: "内容を詳しくご記入ください（5文字以上）",
    submitTicketBtn: "送信する",
    ticketSubmittedMsg: "お問い合わせを受け付けました。近日中にご連絡します！",
    login: "ログイン",
    logout: "ログアウト",
    withdrawAccount: "退会する",
    withdrawModalTitle: "本当に退会しますか？",
    withdrawModalWarning: "退会すると、学習記録、チャットの記憶、日記、単語帳、コインなどすべての個人データが即座に完全に削除され、復元できません。",
    withdrawModalRetentionNotice: "ただし、関連法令によりアカウント識別情報(メールアドレス)は5年間保管された後に破棄されます。",
    withdrawViewFullPolicy: "詳細を見る",
    withdrawPasswordLabel: "パスワード確認",
    withdrawPasswordPlaceholder: "パスワードを入力してください",
    withdrawConfirmBtn: "退会する",
    withdrawCancelBtn: "キャンセル",
    withdrawSuccessMsg: "退会が完了しました。ご利用ありがとうございました。",
    withdrawErrorWrongPassword: "パスワードが正しくありません",

    travel: "韓国旅行",
    selectDestination: "目的地を選択してください",
    whereToGo: "どこへ行きますか？",
    mateAwaits: "目的地を選ぶとキャプテンが待っています",
    openRegions: "開放地域",
    visitedPlaces: "訪問した場所",
    membership: "メンバーシップ",
    boardingPass: "搭乗券 · BOARDING PASS",
    visit: "訪問",
    placesCount: "箇所",
    daysStreak: "日連続",
    premiumOnly: "プレミアム限定",

    chatTitle: "チャット",
    chatSub: "キャプテンとのおしゃべり",
    selectCaptain: "キャプテンを選択してください",
    selectCaptainSub: "各路線のキャプテンとおしゃべりしてみましょう",
    captainBadge: "キャプテン",
    routeLabel: "路線",
    startChat: "💬 会話スタート",
    lockedPremium: "🔒 ロック (プレミアム)",

    seoulRoute: "ソウル・京畿 路線",
    jeonjuRoute: "全州・全羅 路線",
    busanRoute: "釜山・慶南 路線",
    chungcheongRoute: "忠清・公州 路線",
    jejuRoute: "済州島 路線",

    vocabTitle: "単語帳",
    vocabSub: "覚えた韓国語の単語",
    allWords: "すべての単語",
    masteredWords: "マスターした単語",
    practiceVocab: "単語クイズ",

    selectLang: "🌐 言語設定",
    beginnerLearner: "初級学習者",
    coins: "コイン",
    learningStats: "学習統計",
    learnedWords: "学習単語",
    mastered: "マスター",
    wordStatusNew: "新しい単語",
    wordStatusLearning: "学習中",
    wordStatusReview: "復習が必要",
    diaries: "解放日記",
    settings: "設定",
    langSettings: "🌐 言語設定",

    startLearn: "🚀 学習開始！",
    nextChapter: "▶️ 次のチャプターへ",
    backToList: "‹ リストに戻る",
    listen: "🔊 聴く",
    hint: "💡 ヒント",
    skip: "⏭️ スキップ",
    checkAnswer: "正解を確認",
    nextQuestion: "次の問題 →",
    nextWord: "次の単語 →",
    practiceCompleteTitle: "復習完了！",
    practiceCompleteSub: "単語{n}個をすべて復習しました。",
    attemptNotice: "❌ 不正解です！もう一度お試しください。",
    correctNotice: "🎉 正解です！",

    learnTitle: "キャプテンと勉強する",
    tabRegional: "🗺️ 地域文化 (10チャプター)",
    tabSpecial: "⭐ スペシャルテーマ (30チャプター)",
    selectCaptainLearn: "👨‍✈️ 一緒に勉強するキャプテンを選択",
    romanceStory: "❤️ ロマンス (10)",
    dailyStory: "☕ 日常 (10)",
    friendshipStory: "🤝 友情 (10)",
    premiumSpecialMode: "⭐ プレミアムスペシャル",
    totalChapters: "チャプター",
    chapterCount: "段階",
    progressLabel: "現在の進捗",
    ongoing: "進行中",
    completed: "完了",
    locked: "ロック",
    chapterLockedHint: "前のチャプターを先に完了してください",
    regionalChaptersLabel: "地域文化カリキュラム",

    diaryTitle: "日記",
    diarySub: "キャプテンとの思い出日記",
    diaryEmptyMsg: "まだ日記がありません。{name}機長と会話すると日記が書かれます！",
    diaryEmptyBtn: "{name}機長と会話しに行く",
    tabAll: "すべて",
    tabUnlocked: "解放済み",
    tabLocked: "ロック中",
    unlockWithCoins: "コインで解放",
    unlockBtn: "解放する",
    lockedStatus: "ロック中",
    unlockedStatus: "解放済み",

    chooseMate: "メイトを選択",
    freeBadge: "✓ 無料",
    premiumBadge: "⭐ プレミアム",
    chatBtn: "💬 チャット",
    studyBtn: "📖 勉強する",
    diaryBtn: "📔 日記",
    premiumLockedBtn: "🔒 プレミアム限定（ロック中）",
    premiumLockedTitle: "このチャプターはプレミアム限定です",
    premiumLockedSub: "購読するとこのチャプターを学習できます",
    regionHighlights: "見どころ",
    placeGyeongbokgung: "景福宮",
    placeHongdae: "弘大(ホンデ)",
    placeNamsanTower: "南山タワー",
    placeHanokVillage: "韓屋村",
    placeBibimbapStreet: "ビビンバ通り",
    placeGyeonggijeon: "慶基殿",
    placeHaeundae: "海雲台海水浴場",
    placeJagalchiMarket: "チャガルチ市場",
    placeGwanganBridge: "広安大橋",
    placeMuryeongTomb: "武寧王陵",
    placeGongsanseong: "公山城",
    placeGeumgangRiver: "錦江",
    placeSeongsanIlchulbong: "城山日出峰",
    placeHallasan: "漢拏山",
    placeUdoIsland: "牛島",
    romanizationChip: "🔤 ローマ字表記",
    hintChip: "💡 ヒントを見る",
    storySkip: "スキップ ›",
    storyNext: "次へ ▾",
    storyGoToQuiz: "🚀 問題を解きに行く！",
    todaysWords: "今日の単語",
    todaysWordsSub: "今読んだ物語に出てきた単語です。見てみましょう。",
    saveWordsAndQuiz: "単語帳に保存して問題を解く →",
    wordSavedToast: "「{word}」を単語帳に保存しました！",
    sttNotSupportedToast: "このブラウザは音声認識に対応していません。",
    sessionComplete: "学習完了！",
    scoreLabel: "スコア",
    correctLabel: "正解",
    wrongLabel: "不正解",
    coinEarned: "獲得コイン",
    backToChapterList: "📖 チャプター一覧へ",
    chatWithCaptain: "💬 キャプテンとチャット",
    contentNotReadyTitle: "コンテンツ準備中",
    contentNotReadySub: "このチャプターの内容はまだ準備中です。",
    backToMap: "地図に戻る",
    questionsLabel: "問題",
    chancesLabel: "チャンス",
    chancesCount: "3回",
    sessionTagline: "文化と言語を学ぶインタラクティブセッション",
    loadingChapter: "着陸中...",
    loadingChapterDone: "着陸完了!",
    attemptNoticeWithCount: "❌ 不正解です！もう一度お試しください。（残りチャンス：{n}回）",
    checkAnswerWithCount: "正解を確認（チャンス {n}/3）",
    wrongFinalPrefix: "💡 3回失敗 — 正解：",
    speakingCorrect: "🎉 素晴らしい韓国語の発音です！",
    hintShort: "ヒント",
    hintCloseShort: "ヒントを閉じる",
    lockedTitle: "{name}キャプテンのレッスンはロック中",
    lockedDesc: "この路線の学習はプレミアム限定です。ご登録の上ご利用ください。",
    backToMapWithArrow: "← 地図に戻る",
    viewPremiumBtn: "⭐ プレミアムを見る",
    startWithEmail: "✉️ メールで続ける",
    orDivider: "または",
    continueGoogle: "Googleで続ける",
    continueApple: "🍎 Appleで続ける",
    noAccountYet: "アカウントをお持ちでないですか？",
    signUp: "新規登録",
    startHere: "はじめる",
    continueWithAccount: "アカウントで続ける",
    monthlySub: "月額プラン",
    perMonth: "/月",
    cancelAnytime: "いつでも解約可能",
    startPremiumBtn: "⭐ プレミアムを始める",
    alreadyPremiumBtn: "✓ 登録済みです",
    freeTrial: "7日間無料トライアル",
    perkAllMates: "全メイト無制限利用",
    perkAllDiaries: "全メイトの日記を解放可能",
    perkAllChapters: "全チャプター学習",
    perkAllRegions: "全5地域を探訪",
    perkCoinBonus: "コインボーナス+50%",
    perkEarlyAccess: "新コンテンツへの先行アクセス",
    laterBtn: "‹ あとで",
    coinShopTitle: "コインショップ",
    coinPackSmallLabel: "コイン50枚",
    coinPackMediumLabel: "コイン180枚（30枚ボーナス）",
    coinPackLargeLabel: "コイン500枚（100枚ボーナス）",
    coinShopIntro: "コインで日記や機長のフォトアルバムをすぐに解放できます",
    coinShopNotice: "返金はアプリストアのポリシーにより制限される場合があります",
    buyBtn: "購入",
    processingBtn: "処理中...",
    paymentFailedMsg: "決済に失敗しました。",
    cannotOpenPaymentMsg: "決済画面を開けませんでした。",
    serverConnectFailedMsg: "サーバーに接続できませんでした。",
    mailboxTitle: "{name}機長の郵便箱",
    letterMailboxLinkTitle: "郵便箱",
    writeLetterBtn: "手紙を書く",
    noLettersYet: "まだやり取りした手紙がありません",
    sentLetterLabel: "送った手紙",
    replyFromLabel: "{name}機長からの返事",
    waitingReplyMsg: "返事を準備しています",
    checkAfterMsg: "以降に確認してください",
    composeLetterTitle: "{name}機長へ手紙を書く",
    composeLetterSub: "返事は明日のこの時間頃に届きます。",
    composeLetterPlaceholder: "今日あったことや伝えたいことを手紙に書いてみましょう...",
    yourCoinsLabel: "保有コイン",
    cancelBtn: "キャンセル",
    sendLetterBtn: "送る",
    sendingBtn: "送信中...",
    letterSendFailedMsg: "手紙を送れませんでした。",
    backToListBtn: "← リストへ戻る",
    endSessionBtn: "終了",
    diaryLockTitle: "{name}機長の日記はロック中です",
    galleryLockTitle: "{name}機長のフォトアルバムはロック中です",
    lettersLockTitle: "{name}機長の郵便箱はロック中です",
    chatLockTitle: "{name}機長の航路はロック中です",
    chatLockSub: "この航路はプレミアム専用です。サブスクリプションで会話をご利用いただけます。",
    premiumLockSub: "このコンテンツはプレミアム専用です。サブスクリプションまたは個別解放でご利用いただけます。",
    premiumActiveTitle: "プレミアム利用中",
    premiumUpgradeTitle: "プレミアムにアップグレード",
    premiumActiveSub: "全メイト・全チャプター利用可能",
    premiumUpgradeSub: "すべてのメイトに出会い、全チャプターを学びましょう",
    manageArrow: "管理 →",
    viewArrow: "見る →",
    unlockJustOneIntro: "サブスクが負担なら、機長を一人だけ選んで",
    unlockedLabel: "✓ 解放済み",
    notNowBtn: "あとで",
    paywallTitle: "無料会話をすべて使い切りました",
    paywallSub: "無料会員は10回まで会話できます。プレミアムにアップグレードすると{name}機長と自由に会話できます。",
    freeRemainingMsg: "無料会話あと{n}回",
    unlimitedChatLink: "プレミアムで無制限に会話する",
  },
  "zh-TW": {
    home: "首頁",
    map: "旅遊",
    learn: "學習",
    chat: "對話",
    vocab: "生詞本",
    me: "個人中心",
    myPage: "個人中心",
    mateRouteTitle: "與{name}機長的航線",
    changeMate: "更換 ›",
    selectMateTitle: "選擇你的夥伴",
    selectMateSub: "請選擇要一起學習的機長。",
    mateTagline_kyuhyun: "負責首爾·京畿航線的圓滑體貼資深機長",
    mateTagline_haneul: "負責全州·全羅航線的高冷卻又體貼的年下機長",
    mateTagline_sunwoo: "負責釜山·慶南航線的愛開玩笑青梅竹馬機長",
    mateTagline_sangwoo: "負責忠清·公州航線的一絲不苟管制機長",
    mateTagline_yongwoo: "負責濟州航線的傲嬌型兄長般機長",
    loadingTakeoff: "正在準備起飛...",
    galleryTitle: "相簿",
    galleryEmptyMsg: "還沒有準備好的照片。",
    gallerySoftLockNotice: "用金幣解鎖的照片會儲存在您的帳戶中。",

    settingsAccount: "設定 · 帳戶",
    settingsGeneral: "設定 · 一般",
    settingsLegal: "設定 · 法律與支援",
    settingsOther: "其他",
    editProfile: "修改個人資訊",
    paymentMethods: "管理付款方式",
    securitySettings: "安全設定",
    notificationSettings: "通知設定",
    themeSettings: "主題設定",
    themeSettingsSub: "請選擇應用程式的外觀主題。",
    themeLight: "淺色模式",
    themeLightSub: "明亮清爽的畫面",
    themeDark: "深色模式",
    themeDarkSub: "夜間使用更護眼",
    termsOfService: "使用條款",
    privacyPolicy: "隱私權政策",
    customerSupport: "客戶支援",
    appVersion: "應用程式版本",
    backToMyPage: "‹ 返回個人中心",
    savingBtn: "儲存中...",

    nameLabel: "姓名",
    emailLabel: "電子郵件",
    saveChangesBtn: "儲存",
    profileUpdated: "個人資訊已更新。",
    emailInUseError: "此電子郵件已被使用。",
    guestProfileNotice: "訪客狀態下無法修改個人資訊，請先登入。",

    currentPasswordLabel: "目前密碼",
    newPasswordLabel: "新密碼",
    confirmPasswordLabel: "確認新密碼",
    changePasswordBtn: "變更密碼",
    passwordChanged: "密碼已變更。",
    passwordMismatch: "新密碼不一致。",
    passwordTooShort: "密碼至少需要8個字元。",
    noPasswordAccountNotice: "此帳戶（社群/訪客登入）沒有密碼，無法在此變更。",

    notifyChatLabel: "聊天通知",
    notifyChatSub: "機長傳來新訊息時通知我",
    notifyDiaryLabel: "日記通知",
    notifyDiarySub: "有新日記時通知我",
    notifyMarketingLabel: "接收行銷資訊",
    notifyMarketingSub: "接收活動及優惠消息",
    notificationsSaved: "通知設定已儲存。",
    guestNotifyNotice: "訪客狀態下設定不會被儲存，請先登入。",

    noPaymentMethods: "尚未新增任何付款方式。",
    addCardBtn: "新增卡片",
    cardNumberLabel: "卡號",
    cardNumberPlaceholder: "請輸入卡號",
    cardAddedMsg: "卡片已新增。",
    cardRemovedMsg: "卡片已刪除。",
    invalidCardMsg: "無效的卡號。",
    removeCardBtn: "刪除",
    paymentSimNotice: "不會產生實際扣款，完整卡號也不會被儲存。",

    supportSub: "請留下您的問題或困擾，我們確認後會盡快回覆。",
    categoryLabel: "諮詢類型",
    categoryAccount: "帳戶",
    categoryBilling: "付款",
    categoryBug: "錯誤回報",
    categoryContent: "內容",
    messageLabel: "諮詢內容",
    messagePlaceholder: "請詳細描述您的問題（至少5個字元）",
    submitTicketBtn: "送出諮詢",
    ticketSubmittedMsg: "諮詢已送出，我們會盡快確認！",
    login: "登入",
    logout: "登出",
    withdrawAccount: "註銷帳戶",
    withdrawModalTitle: "確定要離開嗎？",
    withdrawModalWarning: "註銷帳戶後，您的學習記錄、聊天記憶、日記、單字本和金幣將立即永久刪除，無法恢復。",
    withdrawModalRetentionNotice: "但根據相關法令，帳戶識別資訊（電子郵件）將保留5年後才會徹底刪除。",
    withdrawViewFullPolicy: "查看詳情",
    withdrawPasswordLabel: "確認密碼",
    withdrawPasswordPlaceholder: "請輸入密碼",
    withdrawConfirmBtn: "註銷帳戶",
    withdrawCancelBtn: "取消",
    withdrawSuccessMsg: "帳戶已註銷。感謝您使用 K-MATE。",
    withdrawErrorWrongPassword: "密碼不正確",

    travel: "韓國旅遊",
    selectDestination: "請選擇目的地",
    whereToGo: "想去哪裡？",
    mateAwaits: "選擇目的地，機長將等待您",
    openRegions: "開放地區",
    visitedPlaces: "已造訪地點",
    membership: "會員等級",
    boardingPass: "登機證 · BOARDING PASS",
    visit: "已造訪",
    placesCount: "處",
    daysStreak: "天連續",
    premiumOnly: "高級會員專屬",

    chatTitle: "對話",
    chatSub: "與機長的韓語心靈對話",
    selectCaptain: "請選擇機長",
    selectCaptainSub: "與各航線機長自由對話",
    captainBadge: "機長",
    routeLabel: "航線",
    startChat: "💬 開始對話",
    lockedPremium: "🔒 未解鎖（高級會員）",

    seoulRoute: "首爾·京畿 航線",
    jeonjuRoute: "全州·全羅 航線",
    busanRoute: "釜山·慶南 航線",
    chungcheongRoute: "忠清·公州 航線",
    jejuRoute: "濟州島 航線",

    vocabTitle: "生詞本",
    vocabSub: "旅行中學到的必備韓語單字",
    allWords: "全部單字",
    masteredWords: "已精通單字",
    practiceVocab: "單字測驗",

    selectLang: "🌐 語言設定（Language Settings）",
    beginnerLearner: "初級學習者",
    coins: "金幣",
    learningStats: "學習統計",
    learnedWords: "已學單字",
    mastered: "已精通",
    wordStatusNew: "新單字",
    wordStatusLearning: "學習中",
    wordStatusReview: "需要複習",
    diaries: "已解鎖日記",
    settings: "設定",
    langSettings: "🌐 語言設定",

    startLearn: "🚀 開始學習！",
    nextChapter: "▶️ 學習下一章",
    backToList: "‹ 返回章節列表",
    listen: "🔊 聽發音",
    hint: "💡 提示",
    skip: "⏭️ 跳過",
    checkAnswer: "核對答案",
    nextQuestion: "下一題 →",
    nextWord: "下一個單字 →",
    practiceCompleteTitle: "複習完成！",
    practiceCompleteSub: "已複習全部 {n} 個單字。",
    attemptNotice: "❌ 答錯了！請再試一次。",
    correctNotice: "🎉 答對了！",

    learnTitle: "與機長一起學習",
    tabRegional: "🗺️ 地區文化（10個章節）",
    tabSpecial: "⭐ 特別主題（30個章節）",
    selectCaptainLearn: "👨‍✈️ 選擇一起學習的機長",
    romanceStory: "❤️ 戀愛故事（10個）",
    dailyStory: "☕ 日常故事（10個）",
    friendshipStory: "🤝 友情故事（10個）",
    premiumSpecialMode: "⭐ 高級會員專屬特輯",
    totalChapters: "章節",
    chapterCount: "關卡",
    progressLabel: "目前進度",
    ongoing: "進行中",
    completed: "已完成",
    locked: "未解鎖",
    chapterLockedHint: "請先完成上一章節",
    regionalChaptersLabel: "機長的地區文化課程",

    diaryTitle: "日記",
    diarySub: "與機長的回憶日記本",
    diaryEmptyMsg: "還沒有日記。和{name}機長聊天就會寫日記喔！",
    diaryEmptyBtn: "去和{name}機長聊天",
    tabAll: "全部",
    tabUnlocked: "已解鎖",
    tabLocked: "未解鎖",
    unlockWithCoins: "用金幣解鎖",
    unlockBtn: "解鎖",
    lockedStatus: "未解鎖",
    unlockedStatus: "已解鎖",

    chooseMate: "選擇夥伴",
    freeBadge: "✓ 免費",
    premiumBadge: "⭐ 高級會員",
    chatBtn: "💬 聊天",
    studyBtn: "📖 學習",
    diaryBtn: "📔 日記",
    premiumLockedBtn: "🔒 僅限高級會員（已鎖定）",
    premiumLockedTitle: "這是高級會員專屬章節",
    premiumLockedSub: "訂閱後即可學習這一章節",
    regionHighlights: "景點",
    placeGyeongbokgung: "景福宮",
    placeHongdae: "弘大",
    placeNamsanTower: "南山塔",
    placeHanokVillage: "韓屋村",
    placeBibimbapStreet: "拌飯街",
    placeGyeonggijeon: "慶基殿",
    placeHaeundae: "海雲台海灘",
    placeJagalchiMarket: "札嘎其市場",
    placeGwanganBridge: "廣安大橋",
    placeMuryeongTomb: "武寧王陵",
    placeGongsanseong: "公山城",
    placeGeumgangRiver: "錦江",
    placeSeongsanIlchulbong: "城山日出峰",
    placeHallasan: "漢拏山",
    placeUdoIsland: "牛島",
    romanizationChip: "🔤 羅馬拼音",
    hintChip: "💡 顯示提示",
    storySkip: "跳過 ›",
    storyNext: "下一步 ▾",
    storyGoToQuiz: "🚀 開始答題！",
    todaysWords: "今日單字",
    todaysWordsSub: "這些是剛才故事裡出現的單字，一起來看看吧。",
    saveWordsAndQuiz: "儲存到單字本並開始答題 →",
    wordSavedToast: "已將「{word}」儲存到單字本！",
    sttNotSupportedToast: "此瀏覽器不支援語音辨識。",
    sessionComplete: "學習完成！",
    scoreLabel: "得分",
    correctLabel: "正確",
    wrongLabel: "錯誤",
    coinEarned: "獲得金幣",
    backToChapterList: "📖 返回章節列表",
    chatWithCaptain: "💬 與機長聊天",
    contentNotReadyTitle: "內容即將上線",
    contentNotReadySub: "此章節的內容尚未準備好。",
    backToMap: "返回地圖",
    questionsLabel: "題目",
    chancesLabel: "機會",
    chancesCount: "3次",
    sessionTagline: "互動式文化與語言學習課程",
    loadingChapter: "降落中...",
    loadingChapterDone: "降落完成!",
    attemptNoticeWithCount: "❌ 答錯了！請再試一次。（剩餘機會：{n}次）",
    checkAnswerWithCount: "核對答案（機會 {n}/3）",
    wrongFinalPrefix: "💡 3次嘗試失敗 — 正確答案：",
    speakingCorrect: "🎉 韓語發音非常棒！",
    hintShort: "提示",
    hintCloseShort: "關閉提示",
    lockedTitle: "{name}機長的課程已鎖定",
    lockedDesc: "此航線的學習內容僅限高級會員使用，請訂閱後使用。",
    backToMapWithArrow: "← 返回地圖",
    viewPremiumBtn: "⭐ 查看高級會員",
    startWithEmail: "✉️ 使用電子郵件繼續",
    orDivider: "或",
    continueGoogle: "使用Google繼續",
    continueApple: "🍎 使用Apple繼續",
    noAccountYet: "還沒有帳號？",
    signUp: "註冊",
    startHere: "開始使用",
    continueWithAccount: "使用帳號繼續",
    monthlySub: "月費訂閱",
    perMonth: "/月",
    cancelAnytime: "隨時可取消",
    startPremiumBtn: "⭐ 開通高級會員",
    alreadyPremiumBtn: "✓ 已訂閱",
    freeTrial: "7天免費試用",
    perkAllMates: "無限暢玩所有夥伴",
    perkAllDiaries: "解鎖所有夥伴的日記",
    perkAllChapters: "學習全部章節",
    perkAllRegions: "探索全部5個地區",
    perkCoinBonus: "所有活動金幣獎勵+50%",
    perkEarlyAccess: "優先體驗新內容",
    laterBtn: "‹ 稍後",
    coinShopTitle: "金幣商店",
    coinPackSmallLabel: "50金幣",
    coinPackMediumLabel: "180金幣（贈30）",
    coinPackLargeLabel: "500金幣（贈100）",
    coinShopIntro: "用金幣立即解鎖日記和機長的照片牆",
    coinShopNotice: "退款可能會依應用程式商店政策受到限制",
    buyBtn: "購買",
    processingBtn: "處理中...",
    paymentFailedMsg: "付款失敗。",
    cannotOpenPaymentMsg: "無法開啟付款視窗。",
    serverConnectFailedMsg: "無法連接伺服器。",
    mailboxTitle: "{name}機長的信箱",
    letterMailboxLinkTitle: "信箱",
    writeLetterBtn: "寫信",
    noLettersYet: "還沒有往來的信件",
    sentLetterLabel: "已寄出的信",
    replyFromLabel: "{name}機長的回信",
    waitingReplyMsg: "正在準備回信",
    checkAfterMsg: "之後請查看",
    composeLetterTitle: "給{name}機長寫信",
    composeLetterSub: "回信將於明天這個時間左右送達。",
    composeLetterPlaceholder: "寫下今天發生的事或想說的話...",
    yourCoinsLabel: "持有金幣",
    cancelBtn: "取消",
    sendLetterBtn: "送出",
    sendingBtn: "傳送中...",
    letterSendFailedMsg: "信件傳送失敗。",
    backToListBtn: "← 返回列表",
    endSessionBtn: "結束",
    diaryLockTitle: "{name}機長的日記已鎖定",
    galleryLockTitle: "{name}機長的相簿已鎖定",
    lettersLockTitle: "{name}機長的信箱已鎖定",
    chatLockTitle: "{name}機長的航線已鎖定",
    chatLockSub: "此航線僅限高級會員使用。訂閱後即可開始對話。",
    premiumLockSub: "此內容僅限高級會員使用。訂閱或單獨解鎖該機長後即可使用。",
    premiumActiveTitle: "高級會員使用中",
    premiumUpgradeTitle: "升級為高級會員",
    premiumActiveSub: "可使用所有夥伴·全部章節",
    premiumUpgradeSub: "認識所有夥伴，學習全部章節",
    manageArrow: "管理 →",
    viewArrow: "查看 →",
    unlockJustOneIntro: "如果訂閱負擔較大，可以只選一位機長解鎖",
    unlockedLabel: "✓ 已解鎖",
    notNowBtn: "以後再說",
    paywallTitle: "免費對話次數已用完",
    paywallSub: "免費會員最多可對話10次。升級為高級會員即可與{name}機長自由對話。",
    freeRemainingMsg: "剩餘{n}次免費對話",
    unlimitedChatLink: "升級高級會員暢聊無限",
  },
  th: {
    home: "หน้าแรก",
    map: "ท่องเที่ยว",
    learn: "เรียนรู้",
    chat: "แชท",
    vocab: "คำศัพท์",
    me: "ฉัน",
    myPage: "หน้าของฉัน",
    mateRouteTitle: "เส้นทางกับกัปตัน{name}",
    changeMate: "เปลี่ยน ›",
    selectMateTitle: "เลือกเพื่อนคู่หูของคุณ",
    selectMateSub: "เลือกกัปตันที่คุณอยากเรียนด้วย",
    mateTagline_kyuhyun: "กัปตันมากประสบการณ์ผู้อ่อนโยนและมีเสน่ห์ ประจำเส้นทางโซล-คย็องกี",
    mateTagline_haneul: "กัปตันรุ่นน้องปากร้ายแต่ใจดี ประจำเส้นทางช็อนจู-ช็อลลา",
    mateTagline_sunwoo: "กัปตันเพื่อนสมัยเด็กขี้เล่น ประจำเส้นทางปูซาน-คย็องนัม",
    mateTagline_sangwoo: "กัปตันควบคุมการบินสายเป๊ะ ประจำเส้นทางชุงช็อง-กงจู",
    mateTagline_yongwoo: "กัปตันสายซึนเดเระเหมือนพี่ชาย ประจำเส้นทางเจจู",
    loadingTakeoff: "กำลังเตรียมออกเดินทาง...",
    galleryTitle: "อัลบั้มภาพ",
    galleryEmptyMsg: "ยังไม่มีภาพที่พร้อมใช้งาน",
    gallerySoftLockNotice: "ภาพที่ปลดล็อกด้วยเหรียญจะถูกบันทึกไว้ในบัญชีของคุณ",

    settingsAccount: "การตั้งค่า · บัญชี",
    settingsGeneral: "การตั้งค่า · ทั่วไป",
    settingsLegal: "การตั้งค่า · กฎหมายและการสนับสนุน",
    settingsOther: "อื่นๆ",
    editProfile: "แก้ไขข้อมูลส่วนตัว",
    paymentMethods: "จัดการวิธีการชำระเงิน",
    securitySettings: "การตั้งค่าความปลอดภัย",
    notificationSettings: "การตั้งค่าการแจ้งเตือน",
    themeSettings: "การตั้งค่าธีม",
    themeSettingsSub: "เลือกธีมที่ต้องการสำหรับแอป",
    themeLight: "โหมดสว่าง",
    themeLightSub: "หน้าจอสว่างสะอาดตา",
    themeDark: "โหมดมืด",
    themeDarkSub: "สบายตาในเวลากลางคืน",
    termsOfService: "ข้อกำหนดการใช้งาน",
    privacyPolicy: "นโยบายความเป็นส่วนตัว",
    customerSupport: "ฝ่ายสนับสนุนลูกค้า",
    appVersion: "เวอร์ชันแอป",
    backToMyPage: "‹ กลับไปหน้าของฉัน",
    savingBtn: "กำลังบันทึก...",

    nameLabel: "ชื่อ",
    emailLabel: "อีเมล",
    saveChangesBtn: "บันทึกการเปลี่ยนแปลง",
    profileUpdated: "อัปเดตข้อมูลส่วนตัวแล้ว",
    emailInUseError: "อีเมลนี้ถูกใช้งานแล้ว",
    guestProfileNotice: "ต้องเข้าสู่ระบบก่อนจึงจะแก้ไขข้อมูลส่วนตัวได้",

    currentPasswordLabel: "รหัสผ่านปัจจุบัน",
    newPasswordLabel: "รหัสผ่านใหม่",
    confirmPasswordLabel: "ยืนยันรหัสผ่านใหม่",
    changePasswordBtn: "เปลี่ยนรหัสผ่าน",
    passwordChanged: "เปลี่ยนรหัสผ่านเรียบร้อยแล้ว",
    passwordMismatch: "รหัสผ่านใหม่ไม่ตรงกัน",
    passwordTooShort: "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
    noPasswordAccountNotice: "บัญชีนี้ (โซเชียล/ผู้เยี่ยมชม) ไม่มีรหัสผ่าน จึงไม่สามารถเปลี่ยนได้ที่นี่",

    notifyChatLabel: "การแจ้งเตือนแชท",
    notifyChatSub: "แจ้งเตือนเมื่อมีข้อความใหม่จากกัปตัน",
    notifyDiaryLabel: "การแจ้งเตือนไดอารี",
    notifyDiarySub: "แจ้งเตือนเมื่อมีไดอารีใหม่ถูกเขียนขึ้น",
    notifyMarketingLabel: "รับข้อมูลการตลาด",
    notifyMarketingSub: "รับข่าวสารกิจกรรมและสิทธิประโยชน์",
    notificationsSaved: "บันทึกการตั้งค่าการแจ้งเตือนแล้ว",
    guestNotifyNotice: "การตั้งค่าจะไม่ถูกบันทึกในสถานะผู้เยี่ยมชม กรุณาเข้าสู่ระบบก่อน",

    noPaymentMethods: "ยังไม่มีวิธีการชำระเงินที่ลงทะเบียนไว้",
    addCardBtn: "เพิ่มบัตร",
    cardNumberLabel: "หมายเลขบัตร",
    cardNumberPlaceholder: "กรอกหมายเลขบัตรของคุณ",
    cardAddedMsg: "เพิ่มบัตรเรียบร้อยแล้ว",
    cardRemovedMsg: "ลบบัตรแล้ว",
    invalidCardMsg: "หมายเลขบัตรไม่ถูกต้อง",
    removeCardBtn: "ลบ",
    paymentSimNotice: "ไม่มีการเรียกเก็บเงินจริง และไม่มีการเก็บหมายเลขบัตรแบบเต็ม",

    supportSub: "แจ้งคำถามหรือปัญหาของคุณ แล้วเราจะตรวจสอบและตอบกลับ",
    categoryLabel: "ประเภทการติดต่อ",
    categoryAccount: "บัญชี",
    categoryBilling: "การชำระเงิน",
    categoryBug: "แจ้งข้อผิดพลาด",
    categoryContent: "เนื้อหา",
    messageLabel: "รายละเอียดการติดต่อ",
    messagePlaceholder: "กรุณาอธิบายปัญหาของคุณโดยละเอียด (อย่างน้อย 5 ตัวอักษร)",
    submitTicketBtn: "ส่งคำถาม",
    ticketSubmittedMsg: "ได้รับคำถามของคุณแล้ว เราจะติดต่อกลับโดยเร็ว!",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    withdrawAccount: "ลบบัญชี",
    withdrawModalTitle: "แน่ใจหรือไม่ว่าต้องการออกไป?",
    withdrawModalWarning: "เมื่อลบบัญชี ความคืบหน้าการเรียน ความทรงจำในแชท ไดอารี่ คลังคำศัพท์ และเหรียญทั้งหมดจะถูกลบทันทีอย่างถาวรและไม่สามารถกู้คืนได้",
    withdrawModalRetentionNotice: "อย่างไรก็ตาม ตามกฎหมาย ข้อมูลระบุตัวตนของบัญชี (อีเมล) จะถูกเก็บไว้ 5 ปีก่อนที่จะลบอย่างถาวร",
    withdrawViewFullPolicy: "ดูรายละเอียด",
    withdrawPasswordLabel: "ยืนยันรหัสผ่าน",
    withdrawPasswordPlaceholder: "กรอกรหัสผ่านของคุณ",
    withdrawConfirmBtn: "ลบบัญชีของฉัน",
    withdrawCancelBtn: "ยกเลิก",
    withdrawSuccessMsg: "บัญชีของคุณถูกลบแล้ว ขอบคุณที่ใช้ K-MATE",
    withdrawErrorWrongPassword: "รหัสผ่านไม่ถูกต้อง",

    travel: "ท่องเที่ยวเกาหลี",
    selectDestination: "เลือกจุดหมายปลายทาง",
    whereToGo: "จะไปที่ไหนดี?",
    mateAwaits: "เลือกจุดหมายปลายทางแล้วกัปตันจะรอคุณอยู่",
    openRegions: "พื้นที่ที่เปิดให้บริการ",
    visitedPlaces: "สถานที่ที่เคยไป",
    membership: "สมาชิก",
    boardingPass: "บัตรขึ้นเครื่อง · BOARDING PASS",
    visit: "เยี่ยมชมแล้ว",
    placesCount: "แห่ง",
    daysStreak: "วันติดต่อกัน",
    premiumOnly: "สำหรับพรีเมียมเท่านั้น",

    chatTitle: "แชท",
    chatSub: "พูดคุยภาษาเกาหลีอย่างอบอุ่นกับกัปตัน",
    selectCaptain: "เลือกกัปตันของคุณ",
    selectCaptainSub: "พูดคุยกับกัปตันของแต่ละเส้นทางได้อย่างอิสระ",
    captainBadge: "กัปตัน",
    routeLabel: "เส้นทาง",
    startChat: "💬 เริ่มแชท",
    lockedPremium: "🔒 ล็อก (พรีเมียม)",

    seoulRoute: "เส้นทางโซล·คย็องกี",
    jeonjuRoute: "เส้นทางจอนจู·จอลลา",
    busanRoute: "เส้นทางปูซาน·คย็องนัม",
    chungcheongRoute: "เส้นทางชุงชอง·กงจู",
    jejuRoute: "เส้นทางเกาะเชจู",

    vocabTitle: "คำศัพท์",
    vocabSub: "คำศัพท์ภาษาเกาหลีที่จำเป็นจากการเดินทาง",
    allWords: "คำศัพท์ทั้งหมด",
    masteredWords: "คำศัพท์ที่เชี่ยวชาญแล้ว",
    practiceVocab: "แบบฝึกหัดคำศัพท์",

    selectLang: "🌐 ตั้งค่าภาษา (Language Settings)",
    beginnerLearner: "ผู้เรียนระดับเริ่มต้น",
    coins: "เหรียญ",
    learningStats: "สถิติการเรียน",
    learnedWords: "คำศัพท์ที่เรียนแล้ว",
    mastered: "เชี่ยวชาญแล้ว",
    wordStatusNew: "คำศัพท์ใหม่",
    wordStatusLearning: "กำลังเรียนรู้",
    wordStatusReview: "ต้องทบทวน",
    diaries: "ไดอารีที่ปลดล็อก",
    settings: "การตั้งค่า",
    langSettings: "🌐 ตั้งค่าภาษา",

    startLearn: "🚀 เริ่มเรียน!",
    nextChapter: "▶️ เรียนบทถัดไป",
    backToList: "‹ กลับไปที่รายการบท",
    listen: "🔊 ฟังเสียง",
    hint: "💡 คำใบ้",
    skip: "⏭️ ข้าม",
    checkAnswer: "ตรวจคำตอบ",
    nextQuestion: "ข้อถัดไป →",
    nextWord: "คำถัดไป →",
    practiceCompleteTitle: "ทบทวนเสร็จแล้ว!",
    practiceCompleteSub: "คุณทบทวนคำศัพท์ครบทั้ง {n} คำแล้ว",
    attemptNotice: "❌ คำตอบผิด! ลองใหม่อีกครั้ง",
    correctNotice: "🎉 ถูกต้อง!",

    learnTitle: "เรียนกับกัปตัน",
    tabRegional: "🗺️ วัฒนธรรมท้องถิ่น (10 บท)",
    tabSpecial: "⭐ หัวข้อพิเศษ (30 บท)",
    selectCaptainLearn: "👨‍✈️ เลือกกัปตันที่จะเรียนด้วยกัน",
    romanceStory: "❤️ เรื่องราวโรแมนติก (10 เรื่อง)",
    dailyStory: "☕ เรื่องราวชีวิตประจำวัน (10 เรื่อง)",
    friendshipStory: "🤝 เรื่องราวมิตรภาพ (10 เรื่อง)",
    premiumSpecialMode: "⭐ โหมดพิเศษพรีเมียม",
    totalChapters: "บท",
    chapterCount: "ขั้นตอน",
    progressLabel: "ความคืบหน้าปัจจุบัน",
    ongoing: "กำลังดำเนินการ",
    completed: "เสร็จสมบูรณ์",
    locked: "ล็อก",
    chapterLockedHint: "กรุณาเรียนบทก่อนหน้าให้จบก่อน",
    regionalChaptersLabel: "หลักสูตรวัฒนธรรมท้องถิ่นของกัปตัน",

    diaryTitle: "ไดอารี",
    diarySub: "สมุดบันทึกความทรงจำกับกัปตัน",
    diaryEmptyMsg: "ยังไม่มีไดอารี พูดคุยกับกัปตัน{name}เพื่อเขียนไดอารี!",
    diaryEmptyBtn: "ไปพูดคุยกับกัปตัน{name}",
    tabAll: "ทั้งหมด",
    tabUnlocked: "ปลดล็อกแล้ว",
    tabLocked: "ล็อกอยู่",
    unlockWithCoins: "ปลดล็อกด้วยเหรียญ",
    unlockBtn: "ปลดล็อก",
    lockedStatus: "ล็อกอยู่",
    unlockedStatus: "ปลดล็อกแล้ว",

    chooseMate: "เลือกเพื่อนคู่หู",
    freeBadge: "✓ ฟรี",
    premiumBadge: "⭐ พรีเมียม",
    chatBtn: "💬 แชท",
    studyBtn: "📖 เรียน",
    diaryBtn: "📔 ไดอารี",
    premiumLockedBtn: "🔒 เฉพาะพรีเมียม (ล็อกอยู่)",
    premiumLockedTitle: "บทนี้สำหรับพรีเมียมเท่านั้น",
    premiumLockedSub: "สมัครสมาชิกเพื่อปลดล็อกบทนี้",
    regionHighlights: "จุดเด่น",
    placeGyeongbokgung: "พระราชวังคย็องบกกุง",
    placeHongdae: "ฮงแด",
    placeNamsanTower: "หอคอยนัมซาน",
    placeHanokVillage: "หมู่บ้านฮันอก",
    placeBibimbapStreet: "ถนนบิบิมบับ",
    placeGyeonggijeon: "คย็องกีจอน",
    placeHaeundae: "หาดแฮอึนแด",
    placeJagalchiMarket: "ตลาดจากัลชี",
    placeGwanganBridge: "สะพานควังอัน",
    placeMuryeongTomb: "สุสานพระเจ้ามูรยอง",
    placeGongsanseong: "ป้อมปราการคงซันซอง",
    placeGeumgangRiver: "แม่น้ำกึมกัง",
    placeSeongsanIlchulbong: "ซองซานอิลชุลบง",
    placeHallasan: "ฮัลลาซาน",
    placeUdoIsland: "เกาะอูโด",
    romanizationChip: "🔤 การถอดเสียงอักษรโรมัน",
    hintChip: "💡 แสดงคำใบ้",
    storySkip: "ข้าม ›",
    storyNext: "ถัดไป ▾",
    storyGoToQuiz: "🚀 เริ่มทำแบบทดสอบ!",
    todaysWords: "คำศัพท์วันนี้",
    todaysWordsSub: "นี่คือคำศัพท์จากเรื่องราวที่คุณเพิ่งอ่านจบ ลองดูกันเลย",
    saveWordsAndQuiz: "บันทึกลงสมุดคำศัพท์แล้วเริ่มทำแบบทดสอบ →",
    wordSavedToast: "บันทึก '{word}' ลงสมุดคำศัพท์แล้ว!",
    sttNotSupportedToast: "เบราว์เซอร์นี้ไม่รองรับการรู้จำเสียงพูด",
    sessionComplete: "เรียนจบแล้ว!",
    scoreLabel: "คะแนน",
    correctLabel: "ถูกต้อง",
    wrongLabel: "ผิด",
    coinEarned: "เหรียญที่ได้รับ",
    backToChapterList: "📖 กลับไปที่รายการบท",
    chatWithCaptain: "💬 แชทกับกัปตัน",
    contentNotReadyTitle: "เนื้อหากำลังจะมาเร็วๆ นี้",
    contentNotReadySub: "เนื้อหาของบทนี้ยังไม่พร้อม",
    backToMap: "กลับไปที่แผนที่",
    questionsLabel: "ข้อ",
    chancesLabel: "โอกาส",
    chancesCount: "3 ครั้ง",
    sessionTagline: "เซสชันเรียนรู้วัฒนธรรมและภาษาแบบอินเทอร์แอกทีฟ",
    loadingChapter: "กำลังลงจอด...",
    loadingChapterDone: "ลงจอดสำเร็จ!",
    attemptNoticeWithCount: "❌ คำตอบผิด! ลองใหม่อีกครั้ง (เหลือโอกาส {n} ครั้ง)",
    checkAnswerWithCount: "ตรวจคำตอบ (โอกาส {n}/3)",
    wrongFinalPrefix: "💡 ลองครบ 3 ครั้งแล้ว — คำตอบ:",
    speakingCorrect: "🎉 การออกเสียงภาษาเกาหลีของคุณยอดเยี่ยมมาก!",
    hintShort: "คำใบ้",
    hintCloseShort: "ปิดคำใบ้",
    lockedTitle: "บทเรียนของกัปตัน{name}ถูกล็อกไว้",
    lockedDesc: "บทเรียนเส้นทางนี้สำหรับพรีเมียมเท่านั้น กรุณาสมัครสมาชิกเพื่อใช้งาน",
    backToMapWithArrow: "← กลับไปที่แผนที่",
    viewPremiumBtn: "⭐ ดูพรีเมียม",
    startWithEmail: "✉️ ดำเนินการต่อด้วยอีเมล",
    orDivider: "หรือ",
    continueGoogle: "ดำเนินการต่อด้วย Google",
    continueApple: "🍎 ดำเนินการต่อด้วย Apple",
    noAccountYet: "ยังไม่มีบัญชีใช่ไหม?",
    signUp: "สมัครสมาชิก",
    startHere: "เริ่มต้นใช้งาน",
    continueWithAccount: "ดำเนินการต่อด้วยบัญชีของคุณ",
    monthlySub: "สมัครสมาชิกรายเดือน",
    perMonth: "/เดือน",
    cancelAnytime: "ยกเลิกได้ทุกเมื่อ",
    startPremiumBtn: "⭐ เริ่มต้นพรีเมียม",
    alreadyPremiumBtn: "✓ สมัครแล้ว",
    freeTrial: "ทดลองใช้ฟรี 7 วัน",
    perkAllMates: "ใช้งานเมทได้ทุกคนไม่จำกัด",
    perkAllDiaries: "ปลดล็อกไดอารี่ของทุกเมท",
    perkAllChapters: "เรียนรู้ทุกบทเรียน",
    perkAllRegions: "สำรวจทั้ง 5 ภูมิภาค",
    perkCoinBonus: "โบนัสเหรียญ +50% ทุกกิจกรรม",
    perkEarlyAccess: "เข้าถึงคอนเทนต์ใหม่ก่อนใคร",
    laterBtn: "‹ ไว้ทีหลัง",
    coinShopTitle: "ร้านเหรียญ",
    coinPackSmallLabel: "เหรียญ 50 เหรียญ",
    coinPackMediumLabel: "เหรียญ 180 เหรียญ (โบนัส 30)",
    coinPackLargeLabel: "เหรียญ 500 เหรียญ (โบนัส 100)",
    coinShopIntro: "ใช้เหรียญปลดล็อกไดอารี่และอัลบั้มภาพของกัปตันได้ทันที",
    coinShopNotice: "การคืนเงินอาจถูกจำกัดตามนโยบายของแอปสโตร์",
    buyBtn: "ซื้อ",
    processingBtn: "กำลังดำเนินการ...",
    paymentFailedMsg: "การชำระเงินล้มเหลว",
    cannotOpenPaymentMsg: "ไม่สามารถเปิดหน้าต่างชำระเงินได้",
    serverConnectFailedMsg: "ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้",
    mailboxTitle: "กล่องจดหมายของกัปตัน{name}",
    letterMailboxLinkTitle: "กล่องจดหมาย",
    writeLetterBtn: "เขียนจดหมาย",
    noLettersYet: "ยังไม่มีจดหมายที่ส่งหากัน",
    sentLetterLabel: "จดหมายที่ส่ง",
    replyFromLabel: "จดหมายตอบจากกัปตัน{name}",
    waitingReplyMsg: "กำลังเตรียมคำตอบ",
    checkAfterMsg: "ลองตรวจสอบอีกครั้งหลังจาก",
    composeLetterTitle: "เขียนจดหมายถึงกัปตัน{name}",
    composeLetterSub: "คำตอบจะมาถึงประมาณเวลานี้ในวันพรุ่งนี้",
    composeLetterPlaceholder: "เขียนเรื่องราววันนี้หรือสิ่งที่อยากบอก...",
    yourCoinsLabel: "เหรียญที่มี",
    cancelBtn: "ยกเลิก",
    sendLetterBtn: "ส่ง",
    sendingBtn: "กำลังส่ง...",
    letterSendFailedMsg: "ส่งจดหมายไม่สำเร็จ",
    backToListBtn: "← กลับไปที่รายการ",
    endSessionBtn: "จบ",
    diaryLockTitle: "ไดอารี่ของกัปตัน{name}ถูกล็อก",
    galleryLockTitle: "อัลบั้มภาพของกัปตัน{name}ถูกล็อก",
    lettersLockTitle: "กล่องจดหมายของกัปตัน{name}ถูกล็อก",
    chatLockTitle: "เส้นทางของกัปตัน{name}ถูกล็อก",
    chatLockSub: "เส้นทางนี้สำหรับสมาชิกพรีเมียมเท่านั้น กรุณาสมัครสมาชิกเพื่อเริ่มสนทนา",
    premiumLockSub: "เนื้อหานี้สำหรับสมาชิกพรีเมียมเท่านั้น กรุณาสมัครสมาชิกหรือปลดล็อกกัปตันคนนี้แยกต่างหาก",
    premiumActiveTitle: "กำลังใช้พรีเมียม",
    premiumUpgradeTitle: "อัปเกรดเป็นพรีเมียม",
    premiumActiveSub: "ใช้ได้ทุกเมท · ทุกบทเรียน",
    premiumUpgradeSub: "พบกับทุกเมทและเรียนรู้ทุกบทเรียน",
    manageArrow: "จัดการ →",
    viewArrow: "ดู →",
    unlockJustOneIntro: "หากการสมัครสมาชิกดูเป็นภาระ ลองปลดล็อกกัปตันเพียงคนเดียว",
    unlockedLabel: "✓ ปลดล็อกแล้ว",
    notNowBtn: "ไว้ทีหลัง",
    paywallTitle: "ใช้ข้อความฟรีหมดแล้ว",
    paywallSub: "สมาชิกฟรีสามารถแชทได้สูงสุด 10 ครั้ง อัปเกรดเป็นพรีเมียมเพื่อพูดคุยกับกัปตัน{name}ได้อย่างอิสระ",
    freeRemainingMsg: "เหลือข้อความฟรีอีก {n} ครั้ง",
    unlimitedChatLink: "แชทไม่จำกัดด้วยพรีเมียม",
  },
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: "ko",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("ko");

  useEffect(() => {
    const saved = localStorage.getItem("kmate_lang") as Language;
    const validLangs: Language[] = ["ko", "en", "ru", "zh", "ja", "zh-TW", "th"];
    if (saved && validLangs.includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  // 앱 전체 최상단 Provider라 여기서 한 번만 실행 — 로그인 안 한 방문자별로 각자의
  // 게스트 계정을 발급받아둔다 (자세한 이유는 lib/auth/store.ts의 ensureGuestAccount 참고).
  useEffect(() => {
    ensureGuestAccount();
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("kmate_lang", lang);
  };

  const t = (key: string, vars?: Record<string, string | number>): string => {
    let str = TRANSLATIONS[language]?.[key] ?? TRANSLATIONS["ko"]?.[key] ?? key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        str = str.split(`{${k}}`).join(String(v));
      }
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
