"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "ko" | "en" | "ru" | "zh" | "ja" | "zh-TW" | "th";

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ko: {
    // Navigation
    home: "홈",
    map: "여행",
    learn: "학습",
    chat: "대화",
    vocab: "단어장",
    me: "나",
    myPage: "마이페이지",
    login: "로그인",
    logout: "로그아웃",

    // Home / Map Page
    travel: "여행하기",
    selectDestination: "목적지를 선택하세요",
    whereToGo: "어디로 떠날까요?",
    mateAwaits: "목적지를 선택하면 메이트가 기다려요",
    openRegions: "개방 지역",
    visitedPlaces: "방문 장소",
    membership: "멤버십",
    boardingPass: "BOARDING PASS · 탑승권",
    visit: "방문",
    placesCount: "곳",
    daysStreak: "일 연속",
    premiumOnly: "프리미엄 전용",

    // Chat Page
    chatTitle: "대화하기",
    chatSub: "기장님과의 감성 한국어 대화",
    selectCaptain: "기장님을 선택하세요",
    selectCaptainSub: "각 노선 기장과 대화해보세요",
    captainBadge: "기장",
    routeLabel: "노선",
    startChat: "💬 대화 시작",
    lockedPremium: "🔒 잠금 (프리미엄)",

    // Routes
    seoulRoute: "서울·경기 노선",
    jeonjuRoute: "전주·전라 노선",
    busanRoute: "부산·경남 노선",
    chungcheongRoute: "충청·공주 노선",
    jejuRoute: "제주 노선",

    // Vocab Page
    vocabTitle: "단어장",
    vocabSub: "여행에서 배운 필수 한국어 단어",
    allWords: "전체 단어",
    masteredWords: "마스터한 단어",
    practiceVocab: "단어 퀴즈 연습",

    // Profile Page
    selectLang: "🌐 언어 설정 (Language Settings)",
    beginnerLearner: "초급 학습자",
    coins: "코인",
    learningStats: "학습 통계",
    learnedWords: "배운 단어",
    mastered: "마스터",
    diaries: "해금 일기",
    settings: "설정",
    langSettings: "🌐 언어 설정",

    // Learn & Exercises
    startLearn: "🚀 학습 시작!",
    nextChapter: "▶️ 다음 챕터 학습하기",
    backToList: "‹ 챕터 목록으로",
    listen: "🔊 들어보기",
    hint: "💡 힌트",
    skip: "⏭️ 스킵",
    checkAnswer: "정답 확인",
    nextQuestion: "다음 문제 →",
    attemptNotice: "❌ 오답입니다! 다시 시도해 보세요.",
    correctNotice: "🎉 정답입니다!",

    // Learn Main Page
    learnTitle: "기장과 공부하기",
    tabRegional: "🗺️ 지역 문화 (10대 챕터)",
    tabSpecial: "⭐ 스페셜 주제별 (30대 챕터)",
    selectCaptainLearn: "👨‍✈️ 함께 공부할 남성 기장님 선택",
    romanceStory: "❤️ 로맨스 스토리 (10개)",
    dailyStory: "☕ 일상 스토리 (10개)",
    friendshipStory: "🤝 친구 스토리 (10개)",
    premiumSpecialMode: "⭐ 프리미엄 스페셜 모드",
    totalChapters: "챕터",
    chapterCount: "단계",
    progressLabel: "현재 진도",
    ongoing: "진행중",
    completed: "완료",
    locked: "잠김",
    regionalChaptersLabel: "기장의 지역 문화 커리큘럼",

    // Diary Page
    diaryTitle: "일기",
    diarySub: "기장님과의 추억 일기장",
    diaryEmptyMsg: "아직 쓴 일기가 없어요. {name} 기장님과 대화를 나누면 일기가 쓰여요!",
    diaryEmptyBtn: "{name} 기장님과 대화하러 가기",
    tabAll: "전체",
    tabUnlocked: "해금",
    tabLocked: "잠금",
    unlockWithCoins: "코인으로 해금",
    unlockBtn: "해금하기",
    lockedStatus: "잠금",
    unlockedStatus: "해금됨",

    chooseMate: "메이트 선택",
    freeBadge: "✓ 무료",
    premiumBadge: "⭐ 프리미엄",
    chatBtn: "💬 대화하기",
    studyBtn: "📖 공부하기",
    diaryBtn: "📔 일기",
    premiumLockedBtn: "🔒 프리미엄 전용 (잠금)",
    regionHighlights: "이 지역 명소",
    romanizationChip: "🔤 발음 그대로 (Romanization)",
    hintChip: "💡 힌트 보기",
    storySkip: "건너뛰기 ›",
    storyNext: "다음 ▾",
    storyGoToQuiz: "🚀 문제 풀러 가기!",
    todaysWords: "오늘의 단어",
    todaysWordsSub: "방금 읽은 이야기에 나온 단어들이에요. 눈에 익혀볼까요?",
    saveWordsAndQuiz: "단어장에 저장하고 문제 풀기 →",
    sessionComplete: "학습 완료!",
    scoreLabel: "점수",
    correctLabel: "정답",
    wrongLabel: "오답",
    coinEarned: "코인 획득",
    backToChapterList: "📖 챕터 목록으로",
    chatWithCaptain: "💬 기장님과 대화하기",
    contentNotReadyTitle: "콘텐츠 준비 중이에요",
    contentNotReadySub: "아직 이 챕터의 콘텐츠가 준비되지 않았어요.",
    backToMap: "지도로 돌아가기",
    questionsLabel: "문제",
    chancesLabel: "기회",
    chancesCount: "3회",
    sessionTagline: "문화와 언어를 함께 배우는 인터랙티브 세션",
    attemptNoticeWithCount: "❌ 오답입니다! 다시 시도해 보세요. (남은 기회: {n}회)",
    checkAnswerWithCount: "정답 확인 (기회 {n}/3)",
    wrongFinalPrefix: "💡 3회 실패 — 정답:",
    speakingCorrect: "🎉 훌륭한 한국어 발음입니다!",
    hintShort: "힌트",
    hintCloseShort: "힌트 닫기",
    lockedTitle: "{name} 기장 학습 잠금",
    lockedDesc: "이 노선의 학습은 프리미엄 전용입니다. 구독 후 이용해 주세요.",
    backToMapWithArrow: "← 지도로 돌아가기",
    viewPremiumBtn: "⭐ 프리미엄 보기",
    startWithEmail: "✉️ 이메일로 계속하기",
    orDivider: "또는",
    continueGoogle: "Google로 계속하기",
    continueApple: "🍎 Apple로 계속하기",
    noAccountYet: "계정이 없으신가요?",
    signUp: "회원가입",
    startHere: "시작하기",
    continueWithAccount: "계정으로 계속하세요",
    monthlySub: "월간 구독",
    perMonth: "/월",
    cancelAnytime: "언제든지 해지 가능 · Cancel anytime",
    startPremiumBtn: "⭐ 프리미엄 시작하기",
    freeTrial: "7일 무료 체험 · 7-day free trial",
    laterBtn: "‹ 나중에",
  },
  en: {
    home: "Home",
    map: "Travel",
    learn: "Learn",
    chat: "Chat",
    vocab: "Vocab",
    me: "My Page",
    myPage: "My Page",
    login: "Login",
    logout: "Logout",

    travel: "Travel Korea",
    selectDestination: "Select your destination",
    whereToGo: "Where to fly?",
    mateAwaits: "Select a destination and your captain awaits",
    openRegions: "Open Regions",
    visitedPlaces: "Visited Places",
    membership: "Membership",
    boardingPass: "BOARDING PASS",
    visit: "Visited",
    placesCount: "Places",
    daysStreak: "day streak",
    premiumOnly: "Premium Only",

    chatTitle: "Chat",
    chatSub: "Talk with your captain",
    selectCaptain: "Choose your Captain",
    selectCaptainSub: "Talk freely with captains of each route",
    captainBadge: "Captain",
    routeLabel: "Route",
    startChat: "💬 Start Chat",
    lockedPremium: "🔒 Locked (Premium)",

    seoulRoute: "Seoul & Gyeonggi Route",
    jeonjuRoute: "Jeonju & Jeolla Route",
    busanRoute: "Busan & Gyeongnam Route",
    chungcheongRoute: "Chungcheong & Gongju Route",
    jejuRoute: "Jeju Island Route",

    vocabTitle: "Vocab",
    vocabSub: "Essential Korean Words",
    allWords: "All Words",
    masteredWords: "Mastered Words",
    practiceVocab: "Vocab Quiz",

    selectLang: "🌐 Language Settings",
    beginnerLearner: "Beginner Learner",
    coins: "Coins",
    learningStats: "Stats",
    learnedWords: "Words",
    mastered: "Mastered",
    diaries: "Diaries",
    settings: "Settings",
    langSettings: "🌐 Language Settings",

    startLearn: "🚀 Start Learning!",
    nextChapter: "▶️ Next Chapter",
    backToList: "‹ Back to List",
    listen: "🔊 Listen",
    hint: "💡 Hint",
    skip: "⏭️ Skip",
    checkAnswer: "Check Answer",
    nextQuestion: "Next Question →",
    attemptNotice: "❌ Incorrect! Try again.",
    correctNotice: "🎉 Correct!",

    learnTitle: "Study with Captain",
    tabRegional: "🗺️ Regional Culture",
    tabSpecial: "⭐ Special Topics",
    selectCaptainLearn: "👨‍✈️ Choose Captain to Study With",
    romanceStory: "❤️ Romance (10)",
    dailyStory: "☕ Daily Life (10)",
    friendshipStory: "🤝 Friendship (10)",
    premiumSpecialMode: "⭐ Premium Special Mode",
    totalChapters: "Chapter",
    chapterCount: "Steps",
    progressLabel: "Progress",
    ongoing: "Ongoing",
    completed: "Done",
    locked: "Locked",
    regionalChaptersLabel: "Regional Culture Curriculum",

    diaryTitle: "Diary",
    diarySub: "Memories with Captain",
    diaryEmptyMsg: "No diary entries yet. Chat with Captain {name} to write one!",
    diaryEmptyBtn: "Chat with Captain {name}",
    tabAll: "All",
    tabUnlocked: "Unlocked",
    tabLocked: "Locked",
    unlockWithCoins: "Unlock with coins",
    unlockBtn: "Unlock",
    lockedStatus: "Locked",
    unlockedStatus: "Unlocked",

    chooseMate: "Choose your mate",
    freeBadge: "✓ Free",
    premiumBadge: "⭐ Premium",
    chatBtn: "💬 Chat",
    studyBtn: "📖 Study",
    diaryBtn: "📔 Diary",
    premiumLockedBtn: "🔒 Premium Only (Locked)",
    regionHighlights: "Highlights",
    romanizationChip: "🔤 Romanization",
    hintChip: "💡 Show Hint",
    storySkip: "Skip ›",
    storyNext: "Next ▾",
    storyGoToQuiz: "🚀 Start the Quiz!",
    todaysWords: "Today's Words",
    todaysWordsSub: "Here are the words from the story you just read. Let's take a look.",
    saveWordsAndQuiz: "Save to Vocab & Start Quiz →",
    sessionComplete: "Session Complete!",
    scoreLabel: "Score",
    correctLabel: "Correct",
    wrongLabel: "Wrong",
    coinEarned: "Coins Earned",
    backToChapterList: "📖 Back to Chapters",
    chatWithCaptain: "💬 Chat with Captain",
    contentNotReadyTitle: "Content Coming Soon",
    contentNotReadySub: "This chapter's content isn't ready yet.",
    backToMap: "Back to Map",
    questionsLabel: "Questions",
    chancesLabel: "Chances",
    chancesCount: "3 tries",
    sessionTagline: "Interactive Culture & Language Session",
    attemptNoticeWithCount: "❌ Incorrect! Try again. ({n} tries left)",
    checkAnswerWithCount: "Check Answer ({n}/3 tries)",
    wrongFinalPrefix: "💡 3 attempts used — Answer:",
    speakingCorrect: "🎉 Excellent Korean pronunciation!",
    hintShort: "Hint",
    hintCloseShort: "Hide Hint",
    lockedTitle: "Captain {name}'s Lessons Locked",
    lockedDesc: "This route's lessons are premium only. Please subscribe to access.",
    backToMapWithArrow: "← Back to Map",
    viewPremiumBtn: "⭐ View Premium",
    startWithEmail: "✉️ Continue with Email",
    orDivider: "or",
    continueGoogle: "Continue with Google",
    continueApple: "🍎 Continue with Apple",
    noAccountYet: "Don't have an account?",
    signUp: "Sign Up",
    startHere: "Get Started",
    continueWithAccount: "Continue with your account",
    monthlySub: "Monthly Subscription",
    perMonth: "/mo",
    cancelAnytime: "Cancel anytime",
    startPremiumBtn: "⭐ Start Premium",
    freeTrial: "7-day free trial",
    laterBtn: "‹ Later",
  },
  ru: {
    home: "Главная",
    map: "Путешествие",
    learn: "Обучение",
    chat: "Чат",
    vocab: "Словарь",
    me: "Профиль",
    myPage: "Моя страница",
    login: "Войти",
    logout: "Выйти",

    travel: "Путешествие по Корее",
    selectDestination: "Выберите направление",
    whereToGo: "Куда отправимся?",
    mateAwaits: "Выберите направление, и капитан будет ждать вас",
    openRegions: "Открытые регионы",
    visitedPlaces: "Посещенные места",
    membership: "Членство",
    boardingPass: "ПОСАДОЧНЫЙ ТАЛОН",
    visit: "Визитов",
    placesCount: "Мест",
    daysStreak: "дней подряд",
    premiumOnly: "Только Премиум",

    chatTitle: "Чат",
    chatSub: "Общение с капитаном",
    selectCaptain: "Выберите капитана",
    selectCaptainSub: "Общайтесь с капитанами рейсов",
    captainBadge: "Капитан",
    routeLabel: "Рейс",
    startChat: "💬 Начать чат",
    lockedPremium: "🔒 Заблокировано (Премиум)",

    seoulRoute: "Рейс Сеул и Кёнги",
    jeonjuRoute: "Рейс Чонджу и Чолла",
    busanRoute: "Рейс Пусан и Кённам",
    chungcheongRoute: "Рейс Чхунчхон и Гонджу",
    jejuRoute: "Рейс о. Чеджу",

    vocabTitle: "Словарь",
    vocabSub: "Корейские слова",
    allWords: "Все слова",
    masteredWords: "Изученные слова",
    practiceVocab: "Викторина слов",

    selectLang: "🌐 Настройки языка",
    beginnerLearner: "Начинающий",
    coins: "Монеты",
    learningStats: "Статистика",
    learnedWords: "Слова",
    mastered: "Изучено",
    diaries: "Дневники",
    settings: "Настройки",
    langSettings: "🌐 Настройки языка",

    startLearn: "🚀 Начать обучение!",
    nextChapter: "▶️ Следующая глава",
    backToList: "‹ К списку глав",
    listen: "🔊 Слушать",
    hint: "💡 Подсказка",
    skip: "⏭️ Пропустить",
    checkAnswer: "Проверить ответ",
    nextQuestion: "Следующий вопрос →",
    attemptNotice: "❌ Неверно! Попробуйте еще раз.",
    correctNotice: "🎉 Верно!",

    learnTitle: "Учеба с капитаном",
    tabRegional: "🗺️ Культура (10 глав)",
    tabSpecial: "⭐ Специальные темы (30 глав)",
    selectCaptainLearn: "👨‍✈️ Выберите капитана для обучения",
    romanceStory: "❤️ Романтика (10)",
    dailyStory: "☕ Повседневность (10)",
    friendshipStory: "🤝 Дружба (10)",
    premiumSpecialMode: "⭐ Премиум спец-режим",
    totalChapters: "Глава",
    chapterCount: "Шагов",
    progressLabel: "Прогресс",
    ongoing: "В процессе",
    completed: "Готово",
    locked: "Закрыто",
    regionalChaptersLabel: "Курс региональной культуры",

    diaryTitle: "Дневник",
    diarySub: "Воспоминания с капитаном",
    diaryEmptyMsg: "Записей пока нет. Поговорите с капитаном {name}, чтобы появилась запись!",
    diaryEmptyBtn: "Поговорить с капитаном {name}",
    tabAll: "Все",
    tabUnlocked: "Открытые",
    tabLocked: "Заблокированные",
    unlockWithCoins: "Разблокировать за монеты",
    unlockBtn: "Разблокировать",
    lockedStatus: "Заблокировано",
    unlockedStatus: "Открыто",

    chooseMate: "Выберите напарника",
    freeBadge: "✓ Бесплатно",
    premiumBadge: "⭐ Премиум",
    chatBtn: "💬 Чат",
    studyBtn: "📖 Учиться",
    diaryBtn: "📔 Дневник",
    premiumLockedBtn: "🔒 Только Премиум (Заблокировано)",
    regionHighlights: "Достопримечательности",
    romanizationChip: "🔤 Транслитерация",
    hintChip: "💡 Показать подсказку",
    storySkip: "Пропустить ›",
    storyNext: "Далее ▾",
    storyGoToQuiz: "🚀 Начать викторину!",
    todaysWords: "Слова сегодняшнего дня",
    todaysWordsSub: "Вот слова из истории, которую вы только что прочитали.",
    saveWordsAndQuiz: "Сохранить слова и начать викторину →",
    sessionComplete: "Урок завершен!",
    scoreLabel: "Очки",
    correctLabel: "Правильно",
    wrongLabel: "Неправильно",
    coinEarned: "Монет получено",
    backToChapterList: "📖 К списку глав",
    chatWithCaptain: "💬 Чат с капитаном",
    contentNotReadyTitle: "Контент скоро появится",
    contentNotReadySub: "Содержание этой главы еще не готово.",
    backToMap: "Вернуться к карте",
    questionsLabel: "Вопросы",
    chancesLabel: "Попытки",
    chancesCount: "3 попытки",
    sessionTagline: "Интерактивный урок культуры и языка",
    attemptNoticeWithCount: "❌ Неверно! Попробуйте еще раз. (Осталось попыток: {n})",
    checkAnswerWithCount: "Проверить ответ (попытка {n}/3)",
    wrongFinalPrefix: "💡 3 неудачные попытки — Ответ:",
    speakingCorrect: "🎉 Отличное произношение корейского!",
    hintShort: "Подсказка",
    hintCloseShort: "Скрыть подсказку",
    lockedTitle: "Уроки капитана {name} заблокированы",
    lockedDesc: "Уроки этого маршрута доступны только по подписке Премиум.",
    backToMapWithArrow: "← Вернуться к карте",
    viewPremiumBtn: "⭐ Смотреть Премиум",
    startWithEmail: "✉️ Продолжить с Email",
    orDivider: "или",
    continueGoogle: "Продолжить с Google",
    continueApple: "🍎 Продолжить с Apple",
    noAccountYet: "Нет аккаунта?",
    signUp: "Регистрация",
    startHere: "Начать",
    continueWithAccount: "Продолжите с аккаунтом",
    monthlySub: "Ежемесячная подписка",
    perMonth: "/мес",
    cancelAnytime: "Отмена в любое время",
    startPremiumBtn: "⭐ Начать Премиум",
    freeTrial: "7 дней бесплатно",
    laterBtn: "‹ Позже",
  },
  zh: {
    home: "首页",
    map: "旅游",
    learn: "学习",
    chat: "对话",
    vocab: "生词本",
    me: "个人中心",
    myPage: "个人中心",
    login: "登录",
    logout: "退出登录",

    travel: "韩国旅游",
    selectDestination: "请选择目的地",
    whereToGo: "想去哪里？",
    mateAwaits: "选择目的地，机长将等待您",
    openRegions: "开放区域",
    visitedPlaces: "打卡地点",
    membership: "会员等级",
    boardingPass: "登机牌 · BOARDING PASS",
    visit: "已打卡",
    placesCount: "处",
    daysStreak: "天连续",
    premiumOnly: "高级会员专属",

    chatTitle: "对话",
    chatSub: "与机长感情韩语对话",
    selectCaptain: "请选择机长",
    selectCaptainSub: "与各航线机长自由对话",
    captainBadge: "机长",
    routeLabel: "航线",
    startChat: "💬 开始对话",
    lockedPremium: "🔒 未解锁 (高级会员)",

    seoulRoute: "首尔·京畿 航线",
    jeonjuRoute: "全州·全罗 航线",
    busanRoute: "釜山·庆南 航线",
    chungcheongRoute: "忠清·公州 航线",
    jejuRoute: "济州岛 航线",

    vocabTitle: "生词本",
    vocabSub: "学习到的韩语单词",
    allWords: "全部单词",
    masteredWords: "已掌握单词",
    practiceVocab: "单词测验",

    selectLang: "🌐 语言设置",
    beginnerLearner: "初级学习者",
    coins: "金币",
    learningStats: "学习统计",
    learnedWords: "已学单词",
    mastered: "已掌握",
    diaries: "解锁日记",
    settings: "设置",
    langSettings: "🌐 语言设置",

    startLearn: "🚀 开始学习！",
    nextChapter: "▶️ 下一章学习",
    backToList: "‹ 返回章节列表",
    listen: "🔊 试听",
    hint: "💡 提示",
    skip: "⏭️ 跳过",
    checkAnswer: "核对答案",
    nextQuestion: "下一题 →",
    attemptNotice: "❌ 回答错误！请再试一次。",
    correctNotice: "🎉 回答正确！",

    learnTitle: "与机长一起学习",
    tabRegional: "🗺️ 地区文化 (10个章节)",
    tabSpecial: "⭐ 特别主题 (30个章节)",
    selectCaptainLearn: "👨‍✈️ 选择一起学习的机长",
    romanceStory: "❤️ 恋爱故事 (10个)",
    dailyStory: "☕ 日常生活 (10个)",
    friendshipStory: "🤝 友情故事 (10个)",
    premiumSpecialMode: "⭐ 高级会员专属特辑",
    totalChapters: "章节",
    chapterCount: "关卡",
    progressLabel: "当前进度",
    ongoing: "进行中",
    completed: "已完成",
    locked: "未解锁",
    regionalChaptersLabel: "地区文化课程",

    diaryTitle: "日记",
    diarySub: "与机长的回忆日记",
    diaryEmptyMsg: "还没有日记。和{name}机长聊天就会写日记哦！",
    diaryEmptyBtn: "去和{name}机长聊天",
    tabAll: "全部",
    tabUnlocked: "已解锁",
    tabLocked: "未解锁",
    unlockWithCoins: "用金币解锁",
    unlockBtn: "解锁",
    lockedStatus: "未解锁",
    unlockedStatus: "已解锁",

    chooseMate: "选择伙伴",
    freeBadge: "✓ 免费",
    premiumBadge: "⭐ 高级会员",
    chatBtn: "💬 聊天",
    studyBtn: "📖 学习",
    diaryBtn: "📔 日记",
    premiumLockedBtn: "🔒 仅限高级会员（已锁定）",
    regionHighlights: "景点",
    romanizationChip: "🔤 罗马拼音",
    hintChip: "💡 显示提示",
    storySkip: "跳过 ›",
    storyNext: "下一步 ▾",
    storyGoToQuiz: "🚀 开始答题！",
    todaysWords: "今日单词",
    todaysWordsSub: "这些是刚才故事里出现的单词，一起来看看吧。",
    saveWordsAndQuiz: "保存到单词本并开始答题 →",
    sessionComplete: "学习完成！",
    scoreLabel: "得分",
    correctLabel: "正确",
    wrongLabel: "错误",
    coinEarned: "获得金币",
    backToChapterList: "📖 返回章节列表",
    chatWithCaptain: "💬 与机长聊天",
    contentNotReadyTitle: "内容即将上线",
    contentNotReadySub: "此章节的内容尚未准备好。",
    backToMap: "返回地图",
    questionsLabel: "题目",
    chancesLabel: "机会",
    chancesCount: "3次",
    sessionTagline: "互动式文化与语言学习课程",
    attemptNoticeWithCount: "❌ 回答错误！请再试一次。（剩余机会：{n}次）",
    checkAnswerWithCount: "核对答案（机会 {n}/3）",
    wrongFinalPrefix: "💡 3次尝试失败 — 正确答案：",
    speakingCorrect: "🎉 韩语发音非常棒！",
    hintShort: "提示",
    hintCloseShort: "关闭提示",
    lockedTitle: "{name}机长的课程已锁定",
    lockedDesc: "该航线的学习内容仅限高级会员使用，请订阅后使用。",
    backToMapWithArrow: "← 返回地图",
    viewPremiumBtn: "⭐ 查看高级会员",
    startWithEmail: "✉️ 使用邮箱继续",
    orDivider: "或",
    continueGoogle: "使用Google继续",
    continueApple: "🍎 使用Apple继续",
    noAccountYet: "还没有账号？",
    signUp: "注册",
    startHere: "开始使用",
    continueWithAccount: "使用账号继续",
    monthlySub: "月度订阅",
    perMonth: "/月",
    cancelAnytime: "随时可取消",
    startPremiumBtn: "⭐ 开通高级会员",
    freeTrial: "7天免费试用",
    laterBtn: "‹ 稍后",
  },
  ja: {
    home: "ホーム",
    map: "旅行",
    learn: "学習",
    chat: "チャット",
    vocab: "単語帳",
    me: "マイページ",
    myPage: "マイページ",
    login: "ログイン",
    logout: "ログアウト",

    travel: "韓国旅行",
    selectDestination: "目的地を選択してください",
    whereToGo: "どこへ行きますか？",
    mateAwaits: "目的地を選ぶとキャプテンが待っています",
    openRegions: "開放地域",
    visitedPlaces: "訪問した場所",
    membership: "メンバーシップ",
    boardingPass: "搭乗券 · BOARDING PASS",
    visit: "訪問",
    placesCount: "箇所",
    daysStreak: "日連続",
    premiumOnly: "プレミアム限定",

    chatTitle: "チャット",
    chatSub: "キャプテンとのおしゃべり",
    selectCaptain: "キャプテンを選択してください",
    selectCaptainSub: "各路線のキャプテンとおしゃべりしてみましょう",
    captainBadge: "キャプテン",
    routeLabel: "路線",
    startChat: "💬 会話スタート",
    lockedPremium: "🔒 ロック (プレミアム)",

    seoulRoute: "ソウル・京畿 路線",
    jeonjuRoute: "全州・全羅 路線",
    busanRoute: "釜山・慶南 路線",
    chungcheongRoute: "忠清・公州 路線",
    jejuRoute: "済州島 路線",

    vocabTitle: "単語帳",
    vocabSub: "覚えた韓国語の単語",
    allWords: "すべての単語",
    masteredWords: "マスターした単語",
    practiceVocab: "単語クイズ",

    selectLang: "🌐 言語設定",
    beginnerLearner: "初級学習者",
    coins: "コイン",
    learningStats: "学習統計",
    learnedWords: "学習単語",
    mastered: "マスター",
    diaries: "解放日記",
    settings: "設定",
    langSettings: "🌐 言語設定",

    startLearn: "🚀 学習開始！",
    nextChapter: "▶️ 次のチャプターへ",
    backToList: "‹ リストに戻る",
    listen: "🔊 聴く",
    hint: "💡 ヒント",
    skip: "⏭️ スキップ",
    checkAnswer: "正解を確認",
    nextQuestion: "次の問題 →",
    attemptNotice: "❌ 不正解です！もう一度お試しください。",
    correctNotice: "🎉 正解です！",

    learnTitle: "キャプテンと勉強する",
    tabRegional: "🗺️ 地域文化 (10チャプター)",
    tabSpecial: "⭐ スペシャルテーマ (30チャプター)",
    selectCaptainLearn: "👨‍✈️ 一緒に勉強するキャプテンを選択",
    romanceStory: "❤️ ロマンス (10)",
    dailyStory: "☕ 日常 (10)",
    friendshipStory: "🤝 友情 (10)",
    premiumSpecialMode: "⭐ プレミアムスペシャル",
    totalChapters: "チャプター",
    chapterCount: "段階",
    progressLabel: "現在の進捗",
    ongoing: "進行中",
    completed: "完了",
    locked: "ロック",
    regionalChaptersLabel: "地域文化カリキュラム",

    diaryTitle: "日記",
    diarySub: "キャプテンとの思い出日記",
    diaryEmptyMsg: "まだ日記がありません。{name}機長と会話すると日記が書かれます！",
    diaryEmptyBtn: "{name}機長と会話しに行く",
    tabAll: "すべて",
    tabUnlocked: "解放済み",
    tabLocked: "ロック中",
    unlockWithCoins: "コインで解放",
    unlockBtn: "解放する",
    lockedStatus: "ロック中",
    unlockedStatus: "解放済み",

    chooseMate: "メイトを選択",
    freeBadge: "✓ 無料",
    premiumBadge: "⭐ プレミアム",
    chatBtn: "💬 チャット",
    studyBtn: "📖 勉強する",
    diaryBtn: "📔 日記",
    premiumLockedBtn: "🔒 プレミアム限定（ロック中）",
    regionHighlights: "見どころ",
    romanizationChip: "🔤 ローマ字表記",
    hintChip: "💡 ヒントを見る",
    storySkip: "スキップ ›",
    storyNext: "次へ ▾",
    storyGoToQuiz: "🚀 問題を解きに行く！",
    todaysWords: "今日の単語",
    todaysWordsSub: "今読んだ物語に出てきた単語です。見てみましょう。",
    saveWordsAndQuiz: "単語帳に保存して問題を解く →",
    sessionComplete: "学習完了！",
    scoreLabel: "スコア",
    correctLabel: "正解",
    wrongLabel: "不正解",
    coinEarned: "獲得コイン",
    backToChapterList: "📖 チャプター一覧へ",
    chatWithCaptain: "💬 キャプテンとチャット",
    contentNotReadyTitle: "コンテンツ準備中",
    contentNotReadySub: "このチャプターの内容はまだ準備中です。",
    backToMap: "地図に戻る",
    questionsLabel: "問題",
    chancesLabel: "チャンス",
    chancesCount: "3回",
    sessionTagline: "文化と言語を学ぶインタラクティブセッション",
    attemptNoticeWithCount: "❌ 不正解です！もう一度お試しください。（残りチャンス：{n}回）",
    checkAnswerWithCount: "正解を確認（チャンス {n}/3）",
    wrongFinalPrefix: "💡 3回失敗 — 正解：",
    speakingCorrect: "🎉 素晴らしい韓国語の発音です！",
    hintShort: "ヒント",
    hintCloseShort: "ヒントを閉じる",
    lockedTitle: "{name}キャプテンのレッスンはロック中",
    lockedDesc: "この路線の学習はプレミアム限定です。ご登録の上ご利用ください。",
    backToMapWithArrow: "← 地図に戻る",
    viewPremiumBtn: "⭐ プレミアムを見る",
    startWithEmail: "✉️ メールで続ける",
    orDivider: "または",
    continueGoogle: "Googleで続ける",
    continueApple: "🍎 Appleで続ける",
    noAccountYet: "アカウントをお持ちでないですか？",
    signUp: "新規登録",
    startHere: "はじめる",
    continueWithAccount: "アカウントで続ける",
    monthlySub: "月額プラン",
    perMonth: "/月",
    cancelAnytime: "いつでも解約可能",
    startPremiumBtn: "⭐ プレミアムを始める",
    freeTrial: "7日間無料トライアル",
    laterBtn: "‹ あとで",
  },
  "zh-TW": {
    home: "首頁",
    map: "旅遊",
    learn: "學習",
    chat: "對話",
    vocab: "生詞本",
    me: "個人中心",
    myPage: "個人中心",
    login: "登入",
    logout: "登出",

    travel: "韓國旅遊",
    selectDestination: "請選擇目的地",
    whereToGo: "想去哪裡？",
    mateAwaits: "選擇目的地，機長將等待您",
    openRegions: "開放地區",
    visitedPlaces: "已造訪地點",
    membership: "會員等級",
    boardingPass: "登機證 · BOARDING PASS",
    visit: "已造訪",
    placesCount: "處",
    daysStreak: "天連續",
    premiumOnly: "高級會員專屬",

    chatTitle: "對話",
    chatSub: "與機長的韓語心靈對話",
    selectCaptain: "請選擇機長",
    selectCaptainSub: "與各航線機長自由對話",
    captainBadge: "機長",
    routeLabel: "航線",
    startChat: "💬 開始對話",
    lockedPremium: "🔒 未解鎖（高級會員）",

    seoulRoute: "首爾·京畿 航線",
    jeonjuRoute: "全州·全羅 航線",
    busanRoute: "釜山·慶南 航線",
    chungcheongRoute: "忠清·公州 航線",
    jejuRoute: "濟州島 航線",

    vocabTitle: "生詞本",
    vocabSub: "旅行中學到的必備韓語單字",
    allWords: "全部單字",
    masteredWords: "已精通單字",
    practiceVocab: "單字測驗",

    selectLang: "🌐 語言設定（Language Settings）",
    beginnerLearner: "初級學習者",
    coins: "金幣",
    learningStats: "學習統計",
    learnedWords: "已學單字",
    mastered: "已精通",
    diaries: "已解鎖日記",
    settings: "設定",
    langSettings: "🌐 語言設定",

    startLearn: "🚀 開始學習！",
    nextChapter: "▶️ 學習下一章",
    backToList: "‹ 返回章節列表",
    listen: "🔊 聽發音",
    hint: "💡 提示",
    skip: "⏭️ 跳過",
    checkAnswer: "核對答案",
    nextQuestion: "下一題 →",
    attemptNotice: "❌ 答錯了！請再試一次。",
    correctNotice: "🎉 答對了！",

    learnTitle: "與機長一起學習",
    tabRegional: "🗺️ 地區文化（10個章節）",
    tabSpecial: "⭐ 特別主題（30個章節）",
    selectCaptainLearn: "👨‍✈️ 選擇一起學習的機長",
    romanceStory: "❤️ 戀愛故事（10個）",
    dailyStory: "☕ 日常故事（10個）",
    friendshipStory: "🤝 友情故事（10個）",
    premiumSpecialMode: "⭐ 高級會員專屬特輯",
    totalChapters: "章節",
    chapterCount: "關卡",
    progressLabel: "目前進度",
    ongoing: "進行中",
    completed: "已完成",
    locked: "未解鎖",
    regionalChaptersLabel: "機長的地區文化課程",

    diaryTitle: "日記",
    diarySub: "與機長的回憶日記本",
    diaryEmptyMsg: "還沒有日記。和{name}機長聊天就會寫日記喔！",
    diaryEmptyBtn: "去和{name}機長聊天",
    tabAll: "全部",
    tabUnlocked: "已解鎖",
    tabLocked: "未解鎖",
    unlockWithCoins: "用金幣解鎖",
    unlockBtn: "解鎖",
    lockedStatus: "未解鎖",
    unlockedStatus: "已解鎖",

    chooseMate: "選擇夥伴",
    freeBadge: "✓ 免費",
    premiumBadge: "⭐ 高級會員",
    chatBtn: "💬 聊天",
    studyBtn: "📖 學習",
    diaryBtn: "📔 日記",
    premiumLockedBtn: "🔒 僅限高級會員（已鎖定）",
    regionHighlights: "景點",
    romanizationChip: "🔤 羅馬拼音",
    hintChip: "💡 顯示提示",
    storySkip: "跳過 ›",
    storyNext: "下一步 ▾",
    storyGoToQuiz: "🚀 開始答題！",
    todaysWords: "今日單字",
    todaysWordsSub: "這些是剛才故事裡出現的單字，一起來看看吧。",
    saveWordsAndQuiz: "儲存到單字本並開始答題 →",
    sessionComplete: "學習完成！",
    scoreLabel: "得分",
    correctLabel: "正確",
    wrongLabel: "錯誤",
    coinEarned: "獲得金幣",
    backToChapterList: "📖 返回章節列表",
    chatWithCaptain: "💬 與機長聊天",
    contentNotReadyTitle: "內容即將上線",
    contentNotReadySub: "此章節的內容尚未準備好。",
    backToMap: "返回地圖",
    questionsLabel: "題目",
    chancesLabel: "機會",
    chancesCount: "3次",
    sessionTagline: "互動式文化與語言學習課程",
    attemptNoticeWithCount: "❌ 答錯了！請再試一次。（剩餘機會：{n}次）",
    checkAnswerWithCount: "核對答案（機會 {n}/3）",
    wrongFinalPrefix: "💡 3次嘗試失敗 — 正確答案：",
    speakingCorrect: "🎉 韓語發音非常棒！",
    hintShort: "提示",
    hintCloseShort: "關閉提示",
    lockedTitle: "{name}機長的課程已鎖定",
    lockedDesc: "此航線的學習內容僅限高級會員使用，請訂閱後使用。",
    backToMapWithArrow: "← 返回地圖",
    viewPremiumBtn: "⭐ 查看高級會員",
    startWithEmail: "✉️ 使用電子郵件繼續",
    orDivider: "或",
    continueGoogle: "使用Google繼續",
    continueApple: "🍎 使用Apple繼續",
    noAccountYet: "還沒有帳號？",
    signUp: "註冊",
    startHere: "開始使用",
    continueWithAccount: "使用帳號繼續",
    monthlySub: "月費訂閱",
    perMonth: "/月",
    cancelAnytime: "隨時可取消",
    startPremiumBtn: "⭐ 開通高級會員",
    freeTrial: "7天免費試用",
    laterBtn: "‹ 稍後",
  },
  th: {
    home: "หน้าแรก",
    map: "ท่องเที่ยว",
    learn: "เรียนรู้",
    chat: "แชท",
    vocab: "คำศัพท์",
    me: "ฉัน",
    myPage: "หน้าของฉัน",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",

    travel: "ท่องเที่ยวเกาหลี",
    selectDestination: "เลือกจุดหมายปลายทาง",
    whereToGo: "จะไปที่ไหนดี?",
    mateAwaits: "เลือกจุดหมายปลายทางแล้วกัปตันจะรอคุณอยู่",
    openRegions: "พื้นที่ที่เปิดให้บริการ",
    visitedPlaces: "สถานที่ที่เคยไป",
    membership: "สมาชิก",
    boardingPass: "บัตรขึ้นเครื่อง · BOARDING PASS",
    visit: "เยี่ยมชมแล้ว",
    placesCount: "แห่ง",
    daysStreak: "วันติดต่อกัน",
    premiumOnly: "สำหรับพรีเมียมเท่านั้น",

    chatTitle: "แชท",
    chatSub: "พูดคุยภาษาเกาหลีอย่างอบอุ่นกับกัปตัน",
    selectCaptain: "เลือกกัปตันของคุณ",
    selectCaptainSub: "พูดคุยกับกัปตันของแต่ละเส้นทางได้อย่างอิสระ",
    captainBadge: "กัปตัน",
    routeLabel: "เส้นทาง",
    startChat: "💬 เริ่มแชท",
    lockedPremium: "🔒 ล็อก (พรีเมียม)",

    seoulRoute: "เส้นทางโซล·คย็องกี",
    jeonjuRoute: "เส้นทางจอนจู·จอลลา",
    busanRoute: "เส้นทางปูซาน·คย็องนัม",
    chungcheongRoute: "เส้นทางชุงชอง·กงจู",
    jejuRoute: "เส้นทางเกาะเชจู",

    vocabTitle: "คำศัพท์",
    vocabSub: "คำศัพท์ภาษาเกาหลีที่จำเป็นจากการเดินทาง",
    allWords: "คำศัพท์ทั้งหมด",
    masteredWords: "คำศัพท์ที่เชี่ยวชาญแล้ว",
    practiceVocab: "แบบฝึกหัดคำศัพท์",

    selectLang: "🌐 ตั้งค่าภาษา (Language Settings)",
    beginnerLearner: "ผู้เรียนระดับเริ่มต้น",
    coins: "เหรียญ",
    learningStats: "สถิติการเรียน",
    learnedWords: "คำศัพท์ที่เรียนแล้ว",
    mastered: "เชี่ยวชาญแล้ว",
    diaries: "ไดอารีที่ปลดล็อก",
    settings: "การตั้งค่า",
    langSettings: "🌐 ตั้งค่าภาษา",

    startLearn: "🚀 เริ่มเรียน!",
    nextChapter: "▶️ เรียนบทถัดไป",
    backToList: "‹ กลับไปที่รายการบท",
    listen: "🔊 ฟังเสียง",
    hint: "💡 คำใบ้",
    skip: "⏭️ ข้าม",
    checkAnswer: "ตรวจคำตอบ",
    nextQuestion: "ข้อถัดไป →",
    attemptNotice: "❌ คำตอบผิด! ลองใหม่อีกครั้ง",
    correctNotice: "🎉 ถูกต้อง!",

    learnTitle: "เรียนกับกัปตัน",
    tabRegional: "🗺️ วัฒนธรรมท้องถิ่น (10 บท)",
    tabSpecial: "⭐ หัวข้อพิเศษ (30 บท)",
    selectCaptainLearn: "👨‍✈️ เลือกกัปตันที่จะเรียนด้วยกัน",
    romanceStory: "❤️ เรื่องราวโรแมนติก (10 เรื่อง)",
    dailyStory: "☕ เรื่องราวชีวิตประจำวัน (10 เรื่อง)",
    friendshipStory: "🤝 เรื่องราวมิตรภาพ (10 เรื่อง)",
    premiumSpecialMode: "⭐ โหมดพิเศษพรีเมียม",
    totalChapters: "บท",
    chapterCount: "ขั้นตอน",
    progressLabel: "ความคืบหน้าปัจจุบัน",
    ongoing: "กำลังดำเนินการ",
    completed: "เสร็จสมบูรณ์",
    locked: "ล็อก",
    regionalChaptersLabel: "หลักสูตรวัฒนธรรมท้องถิ่นของกัปตัน",

    diaryTitle: "ไดอารี",
    diarySub: "สมุดบันทึกความทรงจำกับกัปตัน",
    diaryEmptyMsg: "ยังไม่มีไดอารี พูดคุยกับกัปตัน{name}เพื่อเขียนไดอารี!",
    diaryEmptyBtn: "ไปพูดคุยกับกัปตัน{name}",
    tabAll: "ทั้งหมด",
    tabUnlocked: "ปลดล็อกแล้ว",
    tabLocked: "ล็อกอยู่",
    unlockWithCoins: "ปลดล็อกด้วยเหรียญ",
    unlockBtn: "ปลดล็อก",
    lockedStatus: "ล็อกอยู่",
    unlockedStatus: "ปลดล็อกแล้ว",

    chooseMate: "เลือกเพื่อนคู่หู",
    freeBadge: "✓ ฟรี",
    premiumBadge: "⭐ พรีเมียม",
    chatBtn: "💬 แชท",
    studyBtn: "📖 เรียน",
    diaryBtn: "📔 ไดอารี",
    premiumLockedBtn: "🔒 เฉพาะพรีเมียม (ล็อกอยู่)",
    regionHighlights: "จุดเด่น",
    romanizationChip: "🔤 การถอดเสียงอักษรโรมัน",
    hintChip: "💡 แสดงคำใบ้",
    storySkip: "ข้าม ›",
    storyNext: "ถัดไป ▾",
    storyGoToQuiz: "🚀 เริ่มทำแบบทดสอบ!",
    todaysWords: "คำศัพท์วันนี้",
    todaysWordsSub: "นี่คือคำศัพท์จากเรื่องราวที่คุณเพิ่งอ่านจบ ลองดูกันเลย",
    saveWordsAndQuiz: "บันทึกลงสมุดคำศัพท์แล้วเริ่มทำแบบทดสอบ →",
    sessionComplete: "เรียนจบแล้ว!",
    scoreLabel: "คะแนน",
    correctLabel: "ถูกต้อง",
    wrongLabel: "ผิด",
    coinEarned: "เหรียญที่ได้รับ",
    backToChapterList: "📖 กลับไปที่รายการบท",
    chatWithCaptain: "💬 แชทกับกัปตัน",
    contentNotReadyTitle: "เนื้อหากำลังจะมาเร็วๆ นี้",
    contentNotReadySub: "เนื้อหาของบทนี้ยังไม่พร้อม",
    backToMap: "กลับไปที่แผนที่",
    questionsLabel: "ข้อ",
    chancesLabel: "โอกาส",
    chancesCount: "3 ครั้ง",
    sessionTagline: "เซสชันเรียนรู้วัฒนธรรมและภาษาแบบอินเทอร์แอกทีฟ",
    attemptNoticeWithCount: "❌ คำตอบผิด! ลองใหม่อีกครั้ง (เหลือโอกาส {n} ครั้ง)",
    checkAnswerWithCount: "ตรวจคำตอบ (โอกาส {n}/3)",
    wrongFinalPrefix: "💡 ลองครบ 3 ครั้งแล้ว — คำตอบ:",
    speakingCorrect: "🎉 การออกเสียงภาษาเกาหลีของคุณยอดเยี่ยมมาก!",
    hintShort: "คำใบ้",
    hintCloseShort: "ปิดคำใบ้",
    lockedTitle: "บทเรียนของกัปตัน{name}ถูกล็อกไว้",
    lockedDesc: "บทเรียนเส้นทางนี้สำหรับพรีเมียมเท่านั้น กรุณาสมัครสมาชิกเพื่อใช้งาน",
    backToMapWithArrow: "← กลับไปที่แผนที่",
    viewPremiumBtn: "⭐ ดูพรีเมียม",
    startWithEmail: "✉️ ดำเนินการต่อด้วยอีเมล",
    orDivider: "หรือ",
    continueGoogle: "ดำเนินการต่อด้วย Google",
    continueApple: "🍎 ดำเนินการต่อด้วย Apple",
    noAccountYet: "ยังไม่มีบัญชีใช่ไหม?",
    signUp: "สมัครสมาชิก",
    startHere: "เริ่มต้นใช้งาน",
    continueWithAccount: "ดำเนินการต่อด้วยบัญชีของคุณ",
    monthlySub: "สมัครสมาชิกรายเดือน",
    perMonth: "/เดือน",
    cancelAnytime: "ยกเลิกได้ทุกเมื่อ",
    startPremiumBtn: "⭐ เริ่มต้นพรีเมียม",
    freeTrial: "ทดลองใช้ฟรี 7 วัน",
    laterBtn: "‹ ไว้ทีหลัง",
  },
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: "ko",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("ko");

  useEffect(() => {
    const saved = localStorage.getItem("kmate_lang") as Language;
    const validLangs: Language[] = ["ko", "en", "ru", "zh", "ja", "zh-TW", "th"];
    if (saved && validLangs.includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("kmate_lang", lang);
  };

  const t = (key: string, vars?: Record<string, string | number>): string => {
    let str = TRANSLATIONS[language]?.[key] ?? TRANSLATIONS["ko"]?.[key] ?? key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        str = str.split(`{${k}}`).join(String(v));
      }
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
